commons-bio/src/main/kotlin/ebi/ac/uk/model/File.kt
commons-bio/src/main/kotlin/ebi/ac/uk/paths/FolderResolver.kt
infrastructure/src/main/resources/setup/database/schema.sql
persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt
persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt
persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/File.kt
scheduler/pmc-processor-task/README.md
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt
scheduler/pmc-processor-task/src/main/resources/application.yml
scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt
serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/model/TsvChunk.kt
serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TestFactory.kt
serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/FileXmlDeserializerTest.kt
serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/SectionSerializerTest.kt
submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/MultipartSubmissionResource.kt
submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandler.kt
submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/FilesSource.kt
submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/ResourceFile.kt

- Perform a submission including files
- Add logic to persist the size of the files
- Use security client to get an authenticated web client
- Create configuration variables to set the BioStudies related parameters
- Add a bit of documentation about the processing options to the Read Me file

PMC Submitter Files

---

submission-webapp/build.gradle
submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/FileApiTest.kt
submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupFilesTest.kt
submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionTest.kt
submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt

- added integration test as part of test task
- fixed integration test

Fixed integration test

---

build.gradle.kts
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/PersistenceConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcSubmissionLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/MongoDocService.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/SubmissionDocService.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/docs/FilesProcessedDoc.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/docs/InputFileDoc.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/docs/SubmissionDoc.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/repository/InputFileRepository.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/repository/SubmissionRepository.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/PmcProcessor.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt

- added specialized submission doc service
- minor improvements

added specialized submission doc service

---

scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/common/coroutines/SuspendSequence.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/SubmissionDocService.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/docs/SubmissionDoc.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/ext/MongoCollectionExt.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/repository/SubmissionRepository.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/FileDownloader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/PmcProcessor.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/PmcSubmissionProcessor.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmissionSubmitter.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt

- added channels for pmc processor procesing and submit process

refactor task

---

buildSrc/src/main/kotlin/TestDependencies.kt
commons/commons-transpiler/build.gradle
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/FilesTableGenerator.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/cli/TranspilerCommandLine.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/exception/InvalidColumnException.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/exception/InvalidDirectoryException.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/mapper/FilesTableTemplateMapper.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/processor/FilesTableTemplateProcessor.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/service/FilesTableTemplateTranspiler.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/cli/TranspilerCommandLineTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/factory/FilesTableTemplateFactory.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/mapper/FilesTableTemplateMapperTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/processor/FilesTableTemplateProcessorTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/service/FilesTableTemplateTranspilerTest.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/SubmitterConfig.kt

- Create command line tool for the files table template transpiler
- Process the files contained in the provided path
- Fix bugs in the transpiler
- Improve unit test coverage

Files Table Template Command Line

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSubmission.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Submission.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SubExt.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/persistence/PersistenceContext.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SubExtTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/SerializationService.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/SubTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcSubmissionLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/SubmitterConfig.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Submission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/User.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/test/resources/junit-platform.properties
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/PropertiesProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/validators/ProjectValidator.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/validators/SubmissionValidator.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandlerTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessorTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/validators/ProjectValidatorTest.kt
submission/submitter/src/test/resources/junit-platform.properties

- refactor time procesor
- minor improvements

refactor dates calculation

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Section.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Submission.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/TableModel.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/dsl/SubDslTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/SerializationService.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/common/SerializationFields.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/BuilderSecExtensions.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/XmlSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/serializer/AttributeDetailsSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/serializer/AttributeSerializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/JsonSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/SubTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/XmlSerializerITest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/AttributeXmlDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/AttributeSerializerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt

- Implement equals for Submission class
- Improve logic for sections table header
- Fix several serialization issues
- Add name attributes serialization for TSV
- Add serialize/deserialize test for TSV

Fix Serialization Issues

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Attribute.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Section.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/TableModel.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SectionExt.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SectionExtTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/BuilderSubExtensions.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/TsvToStringSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/serializer/TableSerializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvToStringSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/TableSerializerTest.kt

- Add tests for TSV serializer
- Add value attributes to table headers

TSV Serializer Tests

---

buildSrc/src/main/kotlin/Dependencies.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupFilesTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt

- changed dependencies to use new single artifact
- refactor integration test to use constructor injection

junit upgrade

---

commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/LinkDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/SectionDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/TableJsonDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/SubTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/LinkXmlDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/AttributeSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/SectionSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/SubmissionSerializerTest.kt

Fix broken unit tests and add them to build execution

Unit Tests

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SectionExt.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SubExt.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SectionExtTest.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SubExtTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/JsonSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/TsvSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/ChunkProcessor.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/validation/Errors.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/XmlSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/FileXmlDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/LinkXmlDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/common/BaseXmlDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/exception/InvalidXmlPageTabElementException.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/exception/UnexpectedXmlPageTabElementException.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/LinkXmlDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/XmlDeserializerTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidLibraryFileException.kt

Refactor XML and TSV deserializer to allow single element deserialization

Deserialize Single Element

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/ResourceFile.kt

Fix file text reading to be only on demand

Fix File Reading

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/FileJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/serialization/FileJsonSerializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileDeserializerTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesCopier.kt

Fix files serialization in JSON format

JSON Files Serialization

---

infrastructure/src/main/resources/setup/database/Schema.sql
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Submission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Tag.kt

Rename tags table in order to avoid conflicts with all backend

Rename Tags Table

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGenerator.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGeneratorTest.kt

Fix extension for the generated TSV files

TSV File Extension

---

.gitignore
README.md
submission/submission-webapp/src/main/resources/application-local.yml

Add documentation for local deployment of the submitter web application

Local Deployment Docs

---

commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/exception/InvalidDirectoryException.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/mapper/FilesTableTemplateMapper.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/service/FilesTableTemplateTranspiler.kt
commons/commons-transpiler/src/main/kotlin/ac/uk/ebi/transpiler/validator/FilesTableTemplateValidator.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/mapper/FilesTableTemplateMapperTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/service/FilesTableTemplateTranspilerTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/validator/FilesTableTemplateValidatorTest.kt

Validate that all the paths from the provided template exist and contain files

Files Table Generator

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/errors/InvalidDateFormatException.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SubExt.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SubExtTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/Constants.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/ChunkProcessor.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvSerializationContext.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/validation/Errors.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/SubTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
commons/commons-test/src/main/kotlin/ebi/ac/uk/asserts/SubmissionAssert.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/util/SubmissionInitializer.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/User.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidDateFormatException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessorTest.kt

- Change release date from Instant to LocalDate in order to expect a more possible use case which is "YYYY-MM-DD" instead of expecting the time to be provided
- Add custom exception with a proper error message which indicates the expected format
- Add missing column annotation in the persistence layer
- Add missing configuration properties
- Fix some typos and improve method names

Fix Release Date

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/User.kt

Fix user aux profile column serialization

User Aux Profile

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/FilesSource.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandlerTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/model/FilesSourceTest.kt

- Change MixedFilesSource to be the default implementation of FilesSource and use that instead
- Update unit tests

Unified Files Source

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGenerator.kt

Library file content should be a section, not a plain files table

Library File Serialization

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt
infrastructure/src/main/resources/setup/database/Schema.sql
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/FilesSource.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/model/FilesSourceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/model/UserFilesSourceTest.kt

- Fix file size
- Update library file attribute name

Library File Fixes

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Submission.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGenerator.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/AccessTagProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/AccessTagProcessorTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessorTest.kt

- Private submissions shouldn't inherit the "Public" access tag if its parent if public
- Fix library file serialization
- Fix typos in configuration files

Fix Access Tag

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/Constants.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvDeserializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt

Support for comments in TSV page tab format
Fixes #65

TSV Comments

---

submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/model/api/SecurityUser.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/ProfileService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/ProfileServiceTest.kt

Fix user and groups magic folder generation

Fix Magic Folder

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSection.kt

Fix extended section serialization

Fix Serialization

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt

Use extended section for persistence

Fix Extended Section

---

ci/update.sh
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/ProfileService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/ProfileServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupFilesApiTest.kt

- Add internal application configuration to the starting command
- Fix unit tests
Improve for #63

Submitter Deployment

---

ci/pmc-processor.yml
ci/scheduler.yml
commons/commons-http/build.gradle
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/JacksonFactory.kt
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/slack/Notification.kt
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/slack/NotificationsSender.kt
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/slack/SystemNotification.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PagetabSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/XmlSerializer.kt
scheduler/cluster-client/src/main/kotlin/ac/uk/ebi/cluster/client/lsf/JobConstant.kt
scheduler/cluster-client/src/main/kotlin/ac/uk/ebi/cluster/client/model/Job.kt
scheduler/pmc-processor-task/build.gradle
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/PmcProcessorApp.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/NotificationsConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcSubmissionLoader.kt
scheduler/scheduler/build.gradle
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/common/SchedullerContants.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/common/config/NotificationsConfig.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/common/config/SchedulerConfig.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/common/properties/AppProperties.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/PmcContatants.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/api/PmcImporterResource.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/api/PmcLoaderService.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/domain/PmcLoaderService.kt
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/scheduling/DailyScheduler.kt
scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt
scheduler/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterPropertiesTest.kt

added main notification system

---

submission/submission-webapp/src/main/resources/application.yml

added default smtp

---

ci/update.sh

- added filter expression to ignore remote ports

fixed port overlapping

---

ci/submitter.yml
ci/update.sh
deploy.gradle

- Add support for JVM parameter in the deployment configuration
- Configure Xmx values for beta and prod submitter

Support JVM Configuration

---

ci/submitter.yml
deploy.gradle

Empty JVM Parameters

---

infrastructure/src/main/resources/setup/database/Schema.sql
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/PropertiesProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/PropertiesProcessorTest.kt

Make sure the submission secret key is properly generated

167594936 - Empty Submission Secret Key

---

commons/commons-http/build.gradle
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/servlet/HttpServletResponseExt.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/exception/SecurityException.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/dto/SecurityError.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/exception/SecurityAccessDeniedHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/exception/SecurityAuthEntryPoint.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/exception/SecurityExceptionHandler.kt

https://www.pivotaltracker.com/story/show/168188561
- added specific error security
- added controller advice to provide proper json error message

Feature:168188561:  Submission tool itegration security improvements umbrella ticket

---

client/bio-webclient/build.gradle.kts
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/GroupFilesClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/UserFilesClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/spring/ClientHttpResponse.kt
commons/commons-test/src/main/kotlin/ebi/ac/uk/test/TemporaryFolderExt.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupFilesApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/UserFileApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/GroupFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/UserFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/GroupFilesResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/UserFilesResource.kt

https://www.pivotaltracker.com/story/show/168143247
- added download file support

Pivotal-168143247: Add support for user/group files downloading support

---

buildSrc/src/main/kotlin/Dependencies.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/dsl/SubDsl.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/dsl/SubDslTest.kt
submission/submission-webapp/build.gradle
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/assertions/SubmissionAssertHelper.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/AllInOneSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt

- Improve JSON submission verification
- Add verification for XML and TSV files
- Add utility methods to submission DSL

Fix - Pivotal ID: 168190338 - Submission Files Verification

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SecurityWebClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/User.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/UserExt.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/events/Events.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/model/events/SecurityEvents.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/util/SecurityUtil.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/util/SecurityUtilTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/NotificationConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/notifications/NotificationsSubscriber.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt

https://www.pivotaltracker.com/story/show/168289062
- added activation key
- improved coverage

pivotal-168289062: Include activation token in reset/activate email url

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/RegisterRequest.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/persistence/PersistenceContext.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/IUserPrivilegesService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SecurityTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/UserFileApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/GenericUser.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submitter/build.gradle
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoPatternUtilTest.kt

- Create a service to validate user privileges
- Add validations to allow only super users to provide accession number for submissions
- Update integrations tests to register super users

Feature / Pivotal ID #168317526: Provide Acc No Permission

---

.gitlab-ci.yml
README.md
ci/bio-commandline.yml
client/bio-commandline/README.md
client/bio-commandline/build.gradle.kts
deploy.gradle

- Add documentation for BioStudies CLI (PTSubmit)
- Add page tab specification reference to Read Me document
- Add CI manual step to deploy new CLI versions when required

Pivotal ID # 168477882: Generic Root Section

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/persistence/PersistenceContext.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/AccessPermission.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/IUserPrivilegesService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/GroupFilesApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SecurityTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/UserFileApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/RegularUser.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/SuperUser.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt

- Implement logic to validate whether or not a user should be able to delete a submission
- Add unit and integration tests
- Remove "canDelete" method from PersistenceContext

Pivotal ID # 168537583: Allow Delete Permission

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFileList.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ReferencedFileList.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Section.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Tabular.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFileListTest.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFileTest.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSectionTest.kt

https://www.pivotaltracker.com/story/show/168728488
- added order support

Pivotal Id # 168728488 : Add order field to file list 

---

infrastructure/src/main/resources/setup/database/Dockerfile.test
infrastructure/src/main/resources/setup/database/Sequence.sql
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Counter.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Sequence.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/EmptyAccNoApiTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoProcessorTest.kt

- Fix the problem with the submissions without an accession number
- Create an integration test to validate the scenario

Pivotal ID # 168982339: Empty AccNo

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/ext/JsonNode.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/FileJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/LinkJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/SectionJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/SubmissionJsonDeserializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/SectionDeserializerTest.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/ValidationExceptionHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidSubmissionException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/ValidationException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/TimesProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/processors/AccNoProcessorTest.kt

https://www.pivotaltracker.com/story/show/169289621
- added null handling

Pivotal ID #169289621: Null-Not present submission support

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt

- Fix the access permission query by using the access tag name
- Add integration tests related to access permission tags
- Add an integration test for generic root section
- Add an integration test for submission with tags

Integration Test Special Cases

---

commons/commons-util/gradle.properties
commons/commons-util/src/main/kotlin/ebi/ac/uk/dsl/TsvDsl.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/util/file/ExcelReader.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/util/file/PoiExt.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/PageTabReader.kt

https://www.pivotaltracker.com/story/show/169564754
- fixed line break separation

Pivotal ID # 169564754: File reference is taken as a section

---

.gitlab-ci.yml

Update the Gradle image to 6.0 version

Pivotal ID # 169590703: Gradle Update

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/errors/FileNotFoundException.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/ComposedFileSource.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/ListFilesSource.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/io/sources/ComposedFileSourceTest.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/io/sources/ListFilesSourceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/model/FilesSourceTest.kt

Improve the errors messages displayed when a file doesn't exist

Pivotal ID # 169314354: Improve File Errors

---

buildSrc/src/main/kotlin/Dependencies.kt
client/bio-commandline/build.gradle.kts
infrastructure/src/main/resources/setup/database/Schema.sql

- Add the "ord" column to the ReferencedFile table
- Fix the Log4J libraries import

Minor Fixes

---

client/bio-commandline/src/test/kotlin/ebi/ac/uk/paths/SubmissionFolderResolverTest.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/commons/SubmissionFormat.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/paths/SubmissionFolderResolver.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/integration/SubFormat.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PagetabSerializationService.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PagetabSerializer.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/service/FilesTableTemplateTranspilerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/WebConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/converters/JsonPagetabConverter.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/model/GroupSource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmitResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/converters/JsonPagetabConverterTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/model/GroupSourceTest.kt

https://www.pivotaltracker.com/story/show/169995037

Pivotal ID #169995037: Some groups files are not find

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Attribute.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/Functions.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/TsvChunkLineExt.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/AllInOneSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt

Fix name/value attribute details in the TSV tables

Pivotal ID # 170102525: TSV Table Name/Value Attribute Details

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLineTest.kt

Support operations on behalf other user in PTSubmit

Pivotal ID # 169594303: PTSubmit On Behalf

---

buildSrc/src/main/kotlin/Dependencies.kt
infrastructure/src/main/resources/setup/database/Schema.sql
submission/persistence/build.gradle
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Section.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Submission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/projections/SimpleSubmission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmissionWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionResource.kt

https://www.pivotaltracker.com/story/show/170671004
-added projections support

Pivotal-170671004: Slow submissions retrieval from new submitter

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Submission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/projections/SimpleSubmission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/ProjectRepository.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/util/SecurityUtil.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/converters/BioUserResolver.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ProjectService.kt

https://www.pivotaltracker.com/story/show/169917668
- added no project  handling

Pivotal-169917668: Error fetching projects from new submitter

---

ci/update.sh
submission/submission-webapp/src/main/resources/application.yml

Pivotal #ID 170594671: backend logs into kibana

---

.gitignore
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/ProjectRepository.kt

Fix projects query in order to retrieve only the active ones

Pivotal ID #170872493: Duplicated Projects

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Web.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmissionWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmitResource.kt

Add parameter to allow attaching a direct submission to a project

Pivotal ID # 170872746: Attach Direct Submisson To A Project

---

docs/PULL_REQUEST_TEMPLATE.md

https://www.pivotaltracker.com/story/show/170971914
Create a pull requests template

Pivotal ID # 170971914: Pull Request Template

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/ProjectClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ProjectResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmitResource.kt

https://www.pivotaltracker.com/story/show/170975897
Create an endpoint to attach submissions to a project instead of using the direct submission endpoint with an additional parameter.

Pivotal ID # 170975897: Attach To Endpoint

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Section.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/171058225
- removed column

Pivotal ID # 171058225: Add method db migration

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ProjectService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/processors/IProjectProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ProjectValidationService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ProjectSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/ProjectValidationServiceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/ProjectSubmitterTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/170993540
- Refactor project submitter and processors to use services
- Pass persistence context as a property instead of as a parameter
- Improve variable and classes naming
- Remove unnecessary code

Pivotal ID # 170993540: Refactor Processors To Services

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/GroupFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/UserFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/utils/FileUtils.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/UserFilesResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/TempFileGenerator.kt
submission/submission-webapp/src/main/resources/application.yml

- https://www.pivotaltracker.com/story/show/170971821
- added big file hanldind

Pivotal ID # 170971821: Error uploading big files

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/persistence/PersistenceContext.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/converters/NullableEpochDateConverter.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/converters/EpochDateConverterTest.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/converters/NullableEpochDateConverterTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToProjectsTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/TimesService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ProjectSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/TimesServiceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/ProjectSubmitterTest.kt

https://www.pivotaltracker.com/story/show/171261954
- Add proper release time to the projects
- Fix release time conversion from database to entity
- Add integration tests to cover submissions to projects
Fixes #171261954

Pivotal ID # 171261954: Submission To Private Projects Should Be Private

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Web.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToProjectsTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmissionWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmitResource.kt

https://www.pivotaltracker.com/story/show/170975897
Direct upload now supports any submission attribute
Finishes # 170975897

Pivotal ID # 170975897: Direct Upload Support Submission Attributes

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SwaggerConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/data/web/SubmissionDraftResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/GroupFilesResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/UserFilesResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/groups/web/GroupsResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ProjectResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmitResource.kt

https://www.pivotaltracker.com/story/show/171001599
Complete the documentation for the backend API
Finishes #  171001599

Pivotal ID # 171001599: Complete API Documentation

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt

Calculate proper accession number

Pivotal ID # 171026136: Fix AccNo Calculation

---

submission/submission-webapp/src/main/resources/application.yml

Fix the requireActivation security property name

Fix Security Property Typo

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidPatternException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/util/AccNoPatternUtil.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/util/AccNoPatternUtilTest.kt

Allow superusers to set any accession number

Acc No For Superusers

---

commons/commons-bio/gradle.properties
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/TableModel.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvSerializationContext.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/TsvToStringSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/validation/Errors.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt

**Pivotal Link:** https://www.pivotaltracker.com/story/show/171647484
- Fix parent accNo for TSV section tables
- Validate duplicated accNo for TSV sections
Fixes # 171647484

Pivotal ID # 171647484: TSV Serialization Inconsistency

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/BioWebClient.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/AllInOneSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt

- Use a UTF-8 message converter for the requests made trough the web client
- Add a special character to the all in one submission

Pivotal # 171859281: Special Characters Request

---

buildSrc/src/main/kotlin/Dependencies.kt
submission/submission-webapp/build.gradle.kts
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/resources/application.yml

Register the new submitter in the BioStudies applications dashboard

Pivotal ID # 171884336: Register New Submitter In Dashboard

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SectionExt.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/projections/SimpleSubmission.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SectionExtTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt

https://www.pivotaltracker.com/story/show/170971934
Use the section title for the submission list in case the  submission title is empty

Pivotal ID # 170971934: Use study section title for submission list

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/integration/SerializationConfig.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/FileListSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PageTabSerializationService.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/FileListSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/PageTabSerializationServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/172080341
- Deserialize the file list according to its extension
- The file list format is independent from the submission format
- Add unit and integration tests

Pivotal ID # 172080341: File List Independant Format

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/persistence/model/SubmissionRT.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/persistence/repositories/SubmissionRtRepository.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/persistence/service/NotificationPersistenceService.kt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtSubscriptionServiceTest.kt

Pivotal ID # 138327043: Email User Successful Submission

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/exception/InvalidExtensionException.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/integration/SubFormat.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/FileListSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PageTabSerializationService.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/FileListSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/PageTabSerializationServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/172080341
Improve error message for files with unsupported format

Pivotal ID 172080341: File List Independant Format

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLineTest.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/exception/SecurityWebClientErrorHandler.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/exception/WebClientException.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/ProjectNotFoundException.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/SubmissionNotFoundException.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/GeneralExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/SecurityExceptionWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/SerializationExceptionHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ParentInfoService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ProjectInfoService.kt

https://www.pivotaltracker.com/story/show/172122614
- Improve error catching
- Improve error messages rendering in PTSubmit

Pivotal ID #172122614: Improve Backend Error Messages

---

.gitlab-ci.yml
build.gradle.kts
ci/bio-admin.yml
ci/bio-commandline.yml
ci/pmc-processor.yml
ci/scheduler.yml
ci/submitter.yml

https://www.pivotaltracker.com/story/show/172534817
Configure a single build process to generate the applications artifacts

Pivotal ID # 172534817: Repository Branch Per Environment

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/NotificationProperties.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/NotificationConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/notifications/RtNotificationSubscriber.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/notifications/templates/SuccessfulSubmissionTemplate.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml
submission/submission-webapp/src/main/resources/emails/successful-submission.txt

https://www.pivotaltracker.com/story/show/172620298
Generate the submission URL according to the current environment

Pivotal ID # 172620298: Submission Notification URL

---

buildSrc/src/main/kotlin/Dependencies.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/exception/SecurityWebClientErrorHandler.kt
commons/commons-bio/build.gradle.kts
commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/RegisterRequest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SecurityApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/GeneralExceptionHandler.kt

https://www.pivotaltracker.com/story/show/172475752
Validate user email format upon registration

Pivotal ID # 172475752: Email Validation Signing Up

---

infrastructure/src/main/resources/setup/database/Schema.sql
settings.gradle
submission/stats/build.gradle.kts
submission/stats/src/main/kotlin/uk/ac/ebi/stats/exception/StatNotFoundException.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/exception/SubmissionStatsExceptions.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/mapping/SubmissionStatMapper.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/model/SubmissionStat.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/model/SubmissionStatType.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/persistence/model/SubmissionStatDb.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/persistence/repositories/SubmissionStatsRepository.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/service/SubmissionStatsService.kt
submission/stats/src/test/kotlin/uk/ac/ebi/stats/service/SubmissionStatsServiceTest.kt
submission/submission-webapp/build.gradle.kts
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/StatsConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/stats/web/StatsResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/stats/web/exceptions/InvalidStatException.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/stats/web/handlers/StatsFileHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/web/StatsResourceTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/web/handlers/StatsFileHandlerTest.kt

https://www.pivotaltracker.com/story/show/169759546
- Endpoint to register submission stats
- Implement MockMvc testing
- Update spring boot version in order to support MockMvc Kotlin DSL

Pivotal ID # 169759546: Number of views metadata for each accession

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt

Improve error attaching to projects

Pivotal ID # 172122614: Improve Backend Error Messages

---

infrastructure/src/main/resources/setup/database/Schema.sql
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/filter/PaginationFilter.kt
submission/stats/build.gradle.kts
submission/stats/src/main/kotlin/uk/ac/ebi/stats/persistence/repositories/SubmissionStatsRepository.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/service/SubmissionStatsService.kt
submission/stats/src/test/kotlin/uk/ac/ebi/stats/service/SubmissionStatsServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/StatsConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/stats/web/StatsResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/web/StatsResourceTest.kt

https://www.pivotaltracker.com/story/show/169759546
- Paginate the stats response 
-  Validate that the submission exists before registering the stat

Pivotal ID # 169759546: Add Number Of Views Metadata For Each Accession

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/RegisterRequest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityProperties.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/exception/SecurityException.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/CaptchaVerifier.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/CaptchaVerifierTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/test/SecurityTestEntities.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SecurityApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/exception/SecurityExceptionHandler.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/171570707

Pivotal #ID 171570707: Verify Recaptcha During Sign Up

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/PathResolver.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/common/PathResolver.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/files/web/PathDescriptorResolverTest.kt

https://www.pivotaltracker.com/story/show/173127285
Decode the URL request in the path resolver

Pivotal ID # 173127285: User Files URL Encoding

---

commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ExtFileTestHelper.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtAttributeTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileListTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtLinkTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSectionTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtTableTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToAttributeTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToFileListTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToFileTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToLinkTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToSectionTest.kt

https://www.pivotaltracker.com/story/show/172476764
Include some unit tests missed in the last refactor

Pivotal ID # 172476764: Refresh Interdatabase Support

---

submission/stats/src/main/kotlin/uk/ac/ebi/stats/service/SubmissionStatsService.kt
submission/stats/src/test/kotlin/uk/ac/ebi/stats/service/SubmissionStatsServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/stats/web/StatsResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/web/StatsResourceTest.kt

https://www.pivotaltracker.com/story/show/172889138
Endpoint to increment the stats value

Pivotal ID # 172889138: Stats Increment Endpoint

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt

https://www.pivotaltracker.com/story/show/173321096

Pivotal-173321096: On behalf attribute should not be persisted

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/ResetPasswordRequest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/test/SecurityTestEntities.kt

https://www.pivotaltracker.com/story/show/172933364

Pivotal ID # 172933364: Verify Recaptcha for activation and password recovery forms

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/SubmissionNotFoundException.kt
submission/stats/src/main/kotlin/uk/ac/ebi/stats/service/SubmissionStatsService.kt
submission/stats/src/test/kotlin/uk/ac/ebi/stats/service/SubmissionStatsServiceTest.kt

https://www.pivotaltracker.com/story/show/173383085
- Reduce the number of database calls:
- Summarize the increments before persisting them
- Exclude unnecessary updates from persistence
- Validate submission existence in updates and increments

Pivotal ID # 173383085: Stats Performance Improvement

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FilesService.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FilesServiceTest.kt

https://www.pivotaltracker.com/story/show/173574802

Pivotal #Id: 173574802: Submissions files permissions

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/ProjectExceptions.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ParentInfoService.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/ParentInfoServiceTest.kt

https://www.pivotaltracker.com/story/show/173457329
Validate project access tag at submission time

Pivotal ID # 173457329: Project Access Tag Validation

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityProperties.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-webapp/build.gradle.kts
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/GroupFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/UserFilesService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/utils/MultipartFileUtils.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/173213544

Pivotal-173213544: User files permissions

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/BuilderSecExtensions.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvToStringSerializerTest.kt

https://www.pivotaltracker.com/story/show/173750220
Fix serialization for subsections without accession

Pivotal ID # 173750220: Author TSV Serialization

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/RegisterRequest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/CaptchaVerifier.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/util/SecurityUtil.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/TestConfig.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/DefaultUser.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/RegularUser.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/SuperUser.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/TestGroup.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/entities/TestUser.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/GroupFilesApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/query/ProjectsListTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionDraftListApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/refresh/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneMultipartFileSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToProjectsTest.kt

https://www.pivotaltracker.com/story/show/174054535

 Pivotal ID # 174054535: Disable superUser in request

---

bio-admin/build.gradle.kts
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
scheduler/pmc-processor-task/build.gradle.kts
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/PmcProcessorApp.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/client/PmcApi.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/WebConfig.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/util/FileDownloader.kt
scheduler/scheduler/build.gradle.kts
scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/domain/PmcLoaderService.kt

https://www.pivotaltracker.com/story/show/174076301

Pivotal #Id: 174076301: Update pmc api 

---

ci/submission-handlers.yml
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSection.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSubmission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt

https://www.pivotaltracker.com/story/show/171230259
Improve submission full graph performance
Fixes # 171230259

Pivotal ID # 171230259: Draft creation time outs for big submissions

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContext.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SaveRequest.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSubmission.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbUserData.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/ProjectRepository.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionPersistenceService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/assertions/AllInOneSubmissionHelper.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneMultipartFileSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToProjectsTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/data/service/SubmissionDraftService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/data/service/UserDataService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ProjectService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/169837866

Pivotal #ID: 169837866: Async File Processing

---

infrastructure/src/main/resources/setup/database/Projects.sql
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt

https://www.pivotaltracker.com/story/show/169837866
- Fix SQL queries
- Add missing field for default project

Pivotal ID # 169837866: Async File Processing

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/refresh/SubmissionRefreshApiTest.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/174275207
- Remove persistence layer assertions
- Remove deprecated methods
- Remove unnecessary configuration properties
Delivers # 174275207

Pivotal ID # 174275207: Test Using The Persistence Layer

---

ci/update.sh
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionSubmitted.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/ApplicationConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt

https://www.pivotaltracker.com/story/show/174621725
- Use the proper URL for the submission notifications
- Use the application name instead of the port to kill the process
Fixes # 174621725

Pivotal ID # 174621725: Wrong Notifications URL

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/data/service/SubmissionDraftService.kt

https://www.pivotaltracker.com/story/show/174697743

Pivotal-174697743: Delete draft missing transaction

---

build.gradle.kts
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionPersistenceService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/174801815
Add support to resubmit deleted submissions
Fixes # 174801815

Pivotal ID # 174801815: Permissions For Deleted Submissions

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionMessage.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/config/EventsPublisherConfig.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SubmissionReleaseTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtNotificationService.kt
submission/notifications/src/main/resources/templates/release-notification.txt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtNotificationServiceTest.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/LogSubmissionListener.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/172671360
Upcoming releases RT notifications

Pivotal ID # 172671360: Warn Users About Upcoming Releases

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionSubmitted.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt

https://www.pivotaltracker.com/story/show/173783625
Add the current timestamp to the submission submitted event
Delivers #173783625

Pivotal ID # 173783625: Partial Updates Timestamp

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSubmissionMapper.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/helpers/SourceGenerator.kt

https://www.pivotaltracker.com/story/show/174922363

Pivotal #ID : 174922363: Add support for previous submission files source

---

client/fire-webclient/build.gradle.kts
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/api/FireClient.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/exception/FireClientException.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/exception/FireWebClientErrorHandler.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/ext/MetadataEntryExt.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireOperations.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireWebClient.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/FileSystemEntry.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/FireFile.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/MetadataEntry.kt
client/fire-webclient/src/test/kotlin/uk/ac/ebi/fire/client/api/FireClientTest.kt
client/fire-webclient/src/test/kotlin/uk/ac/ebi/fire/client/ext/MetadataEntryExtTest.kt
settings.gradle
submission/submission-webapp/build.gradle.kts
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/WebConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/property/ApplicationProperties.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/FireExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/FireResource.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/173817309
- Web client for the FIRE API
- Add configuration properties for the FIRE service
Delivers # 173817309

Pivotal ID # 173817309: FIRE Client

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/HardLinkFileVisitor.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FileSystemService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FtpFilesService.kt
submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FtpFilesServiceTest.kt

Generate the FTP hard links with the proper permissions for directories and files

Pivotal ID # 171026062: FTP Hard Links

---

commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbUser.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/GroupService.kt

https://www.pivotaltracker.com/story/show/174274579

Pivotal #Id: 174274579: User eager groups

---

commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt

Pivotal ID # 172671360: Fix Broken Test

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/ConcurrentProcessingSubmissionException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

Validate a submission doesn't have a current processing version before accepting a new submission request

Pivotal ID # 175359447: Async Concurrent Processing Submission

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt

- Validate all other possible submission statuses
- Avoid calculating the MD5 every time an ExtFile is instantiated

Pivotal ID # 175359447: Async Concurrent Processing Submission [HotFix] 

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/SequenceNotFoundException.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/175266840
- Generate next sequence having in mind the already existing submissions
- Move concurrent processing submissions validation to the web handler level
- Improve concurrent validation query
- Validate the sequence exists

Pivotal ID # 175266840: Manual Set AccNo Sequence [HotFix BETA]

---

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/SequenceNotFoundException.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/PersistenceContextImpl.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/SubmissionSqlQueryService.kt
submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/175266840
- Generate next sequence having in mind the already existing submissions
- Move concurrent processing submissions validation to the web handler level
- Improve concurrent validation query
- Validate the sequence exists

Pivotal ID # 175266840: Manual Set AccNo Sequence [HotFix PROD]

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/constants/ExtSerializationFields.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtFileSerializer.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtFileSerializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtFilesTableSerializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtSectionSerializerTest.kt

https://www.pivotaltracker.com/story/show/175101522
Add file path to the extended model

Pivotal ID # 175101522: File Path Field

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SubmissionSqlPersistenceService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/175926073

Pivotal #Id: 175926073: Simplify accNoService

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtAttribute.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFile.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtLink.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSection.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtStat.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSubmissionMapper.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/Model.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtAttributeTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtLinkTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSectionTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtStatTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/AttributeTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/FileTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/LinkTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/SectionTestHelper.kt

- Complete the mapper logic
- Add unit testing

Pivotal ID # 175163839: Mongo To Ext Submission Mapping

---

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/config/SqlPersistenceConfig.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SqlPersistenceService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SqlSubmissionRequestService.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SqlPersistenceServiceTest.kt

https://www.pivotaltracker.com/story/show/175632448

Pivotal #Id : 175632448: Extra persistence layer interfaces to avoid dependencies on SQL classes

---

scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/properties/AppProperties.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/scheduling/DailyScheduler.kt
scheduler/scheduler/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/172671360
Fix scheduler properties

Pivotal ID # 172671360: Warn Users About Upcoming Public Release 

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidPermissionsException.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt

- Fix permissions validation for a regular user resubmission
- Improve the exception name and error message

Pivotal ID # 175632448: Regular User Resubmission

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializer.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/EitherExtTypeDeserializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFilesTableDeserializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializerTest.kt
commons/commons-serialization-util/src/main/kotlin/uk/ac/ebi/serialization/extensions/JsonNode.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/exception/NoAttributeValueException.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/LinkDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/SectionDeserializerTest.kt

Promote To BETA

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/dsl/SubDsl.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Attribute.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/JsonSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDetailJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeJsonDeserializerHelper.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDetailDeserializerTest.kt
infrastructure/src/main/resources/setup/database/Schema.sql
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/converters/AttributeDetailConverter.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFile.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtLink.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSection.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSubmissionMapper.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/FileExt.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/LinkExt.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/ReferencedFileExt.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SectionExt.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SubmissionExt.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/converters/AttributeDetailConverterTest.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/FileExtTest.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/LinkExtTest.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/ReferencedFileExtTest.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SectionExtTest.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/model/ext/SubmissionExtTest.kt

https://www.pivotaltracker.com/story/show/172671360
- Create extension to filter out attributes with no value
- Update schema to avoid null attribute values on the database

Pivotal ID # 172671360: Ignore Empty Value Attributes

---

client/bio-webclient-demo/build.gradle.kts
client/bio-webclient-demo/src/main/kotlin/ac/uk/ebi/biostd/client/demo/SimpleSubmissionDslExample.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/dsl/SubDsl.kt
settings.gradle

https://www.pivotaltracker.com/story/show/176018722

Pivotal-176018722: Add BioStudies client examples for external users

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/AccessType.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/model/api/RefreshUserRequest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/UserResource.kt

Pivotal ID # 176377544: Add refresh users directory structure api endpoint
https://www.pivotaltracker.com/story/show/176377544
Delivers # 176377544

Pivotal ID # 176377544: Add refresh users directory structure api endpoint

---

.gitlab-ci.yml
submission/persistence-mongo/build.gradle.kts
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/MongoDbConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/commons/ExtendedUpdate.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbReposConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/config/SqlPersistenceConfig.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SubmissionSqlPersistenceService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/PersistenceConfig.kt
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/176479473

Pivotal #ID 176479473:  Migrate biostudies test to TestContainers

---

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepositoryTest.kt

https://www.pivotaltracker.com/story/show/176670057
- added logic to update modification date on deletion

Pivotal #ID: 176670057 Modification date needs to be changed when submission is deleted

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/SubmissionMongoRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/SubmissionProjects.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/doc/SubmissionDocTestHelper.kt

- added access tag query support

Pivotal ID # 176479720: Mongo Metadata Query

---

.gitlab-ci.yml
gradle/itest.gradle.kts
infrastructure/src/main/resources/setup/database/Schema.sql
submission/submission-webapp/gradle.properties
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/refresh/SubmissionRefreshApiTest.kt
submission/submission-webapp/src/itest/resources/application.yml

https://www.pivotaltracker.com/story/show/176779952
- Use a Gradle property to decide whether to run the tests in Mongo or MySQL
- Run both types of integration tests in the CI
- Load the schema for the MySQL database container from a proper SQL script
- Remove unused database column

Pivotal ID # 176779952: Mongo iTests CI

---

scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/PersistenceConfig.kt
scheduler/pmc-processor-task/src/main/resources/application.yml
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/pmc/importer/api/PmcProcessorProp.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/pmc/importer/domain/PmcLoaderService.kt
scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt
scheduler/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterPropertiesTest.kt

https://www.pivotaltracker.com/story/show/176838189

Pivotal #ID 176838189: Rename PMC mongo collections

---

submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt

https://www.pivotaltracker.com/story/show/175894089

Pivotal ID #175894089: Check if queues in RabbitMQ are persistent

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/from/DocSectionConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/SectionConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocSubmissionMapper.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSection.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionModel.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/SectionConverterTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/SectionTestHelper.kt

https://www.pivotaltracker.com/story/show/177074116

Pivotal ID #177074116 : model table section properly

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionDraft.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoServiceTest.kt

https://www.pivotaltracker.com/story/show/177042374
Fix update draft endpoint in mongo

Pivotal ID # 177042374: Delete Draft After Submission (#342)

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryServiceTest.kt

https://www.pivotaltracker.com/n/projects/1189310
Persist submission draft when it doesn't exist

Pivotal ID # 177042374: Delete Draft After Submission

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryServiceTest.kt

https://www.pivotaltracker.com/story/show/177193125

Pivotal #ID 177193125: Improve collection template validation

---

scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/client/PmcApi.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/FileSpec.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/load/PmcSubmissionLoader.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/InputFilesDocService.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/process/util/FileDownloader.kt
scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt

https://www.pivotaltracker.com/story/show/177076728

Pivotal #ID 177076728: Use PMC new streaming API

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/176501169
Fix extended submission client pagination

Pivotal ID # 176501169: FTP Folders Missing

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/WebClientCommon.kt
scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt
submission/persistence-common/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/filesystem/PageTabService.kt
submission/persistence-common/src/test/kotlin/ac/uk/ebi/biostd/persistence/common/filesystem/FilesServiceTest.kt
submission/persistence-common/src/test/kotlin/ac/uk/ebi/biostd/persistence/common/filesystem/PageTabServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/177477471
Move the file lists provided by the user inside the submission files folder

Pivotal ID # 177477471: Move File Lists to Files Folder

---

.gitlab-ci.yml
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/serialization/SubmissionJsonSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/Functions.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/serialization/SubmissionJsonSerializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvSingleElementDeserializationTest.kt

https://www.pivotaltracker.com/story/show/177413282
Ignore empty attributes in TSV deserialization

Pivotal ID #177413282: TSV Tables Empty First Attribute Value

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Parameters.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/DeletionRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/MigrationRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/SubmissionRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/177304040
Create an operation in PT submit to migrate a submission from one environment to another

Pivotal ID # 177304040: PT Submit Migration Operation

---

.gitlab-ci.yml
README.md
ci/submitter.yml
client/bio-commandline/README.md
deploy.gradle

https://www.pivotaltracker.com/story/show/177304040
- Increase submitter RAM
- Update deployment artifact name for BioStudies CLI

Pivotal ID # 177304040: Fix Build

---

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/exception/SecurityException.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/web/SecurityFilter.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityQueryServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/177304040
- Validate owner user and collection exists when submitting extended
- Update the submitter of the submission when it's submitted through the extended submission API
- Refactor security functions related to query
- Optimize method calls

Pivotal ID # 177304040: Validate Extended Submission

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt

https://www.pivotaltracker.com/story/show/177536825

Throw SubmissionNotFoundException if submission is not found in mongo

---

commons/commons-http/gradle.properties
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/slack/NotificationsSender.kt
commons/commons-http/src/test/kotlin/ebi/ac/uk/commons/http/slack/NotificationsSenderTest.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/FailedSubmissionRequestMessage.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/config/EventsPublisherConfig.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/NotificationProperties.kt
submission/submission-handlers/build.gradle.kts
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/ApplicationConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/main/resources/application.yml
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/177413307
- Slack notification for submission with errors at processing level
- Create a new queue to log the problems in order to be used for later verification

Pivotal ID # 177413307: Report Submissions With Errors

---

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/validator/collection/EuToxRiskValidator.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/validator/collection/EuToxRiskValidatorTest.kt

https://www.pivotaltracker.com/story/show/177756846

Pivotal ID #177756846: Allow to bypass toxic risk validation when QMRF-ID attribute

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/request/PaginationFilter.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/request/SubmissionFilter.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbReposConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionExt.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt

https://www.pivotaltracker.com/story/show/178028214

Pivotal ID # 178028214: Show requests in submissions list endpoint

---

commons/commons-model-extended-serialization/build.gradle.kts
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializer.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileListDeserializer.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializer.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SubmissionSqlPersistenceService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/from/ToDbSubmissionMapper.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/from/ToDbSubmissionMapperTest.kt

https://www.pivotaltracker.com/story/show/177979104
- added custom serializers
- added support to reloading after request processing to guarantee the last version of the information available is stored.

Pivotal ID#  177979104:Issues submitting S-BIAD116

---

client/bio-commandline/README.md
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Parameters.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Utils.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/DeletionRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/MigrationRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/SubmissionRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt

https://www.pivotaltracker.com/story/show/177844724

Pivotal ID #177844724: Allow move submissions with diferent owner

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt

https://www.pivotaltracker.com/story/show/178315201
A collection shouldn't be required to exist before it's created

Pivotal ID # 178315201: Migrate Collections

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/ActivateByEmailRequest.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SecurityNotification.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/SecurityNotificationService.kt
submission/notifications/src/main/resources/templates/activation-by-email.html
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/SecurityNotificationServiceTest.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SecurityNotificationListener.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/test/SecurityTestEntities.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt

- Create an endpoint to activate users by email
- Improve response given by the "check-registration" endpoint

Pivotal ID # 178213145: Activate ArrayExpress inactive users

---

.gitlab-ci.yml
gradle/itest.gradle.kts
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFileList.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSection.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtFileListTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt

- Fix typo in the testing mode system property
- Adjust tests

Pivotal ID # 177839881: iTest Property Typo

---

.gitlab-ci.yml
commons/commons-test/src/main/kotlin/ebi/ac/uk/db/DatabaseConstants.kt
scheduler/pmc-processor-task/src/test/kotlin/ac/uk/ebi/pmc/PmcFileLoaderTest.kt
scheduler/pmc-processor-task/src/test/kotlin/ac/uk/ebi/pmc/PmcSubmissionSubmitterTest.kt
scheduler/pmc-processor-task/src/test/kotlin/ac/uk/ebi/pmc/PmcSubmissionTabProcessorTest.kt
scheduler/pmc-processor-task/src/test/kotlin/ac/uk/ebi/pmc/migrations/PMCDatabaseChangeLogTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionStatsDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/StatsMongoDataServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/FileTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/SectionTestHelper.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/GroupFilesApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/InvalidPermissionsException.kt

- Add initialization strategy for all the tests using Mongo containers
- Fix warnings
- Adjust coding standards

Pivotal ID # 177839881: Mongo Mode iTests

---

build.gradle.kts
submission/submission-webapp/build.gradle.kts

https://www.pivotaltracker.com/story/show/178375625
Actuator Git commit plugin

Pivotal ID # 178375625: Actuator Git Commit

---

client/bio-commandline/README.md
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/GrantPermissionCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/PermissionRequest.kt

https://www.pivotaltracker.com/story/show/178446609
- Add documentation for the new operation
- Remove unnecessary property

Pivotal #ID 178446609: BioCommandLine Grant Permissions

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SecurityNotification.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/UserActivationTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/SecurityNotificationService.kt
submission/notifications/src/main/resources/templates/activation-by-email.html
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/SecurityNotificationServiceTest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt

https://www.pivotaltracker.com/story/show/179055347
* Add activation code to AE user activation email
Finishes #179055347

Pivotal ID # 179055347: Update AE user activation email

---

ci/update.sh

https://www.pivotaltracker.com/story/show/179105055
Update Java Home location

Pivotal ID # 179105055: Update Java Home

---

ci/update.sh

Pivotal ID # 179105055: Update Java Home BETA

---

ci/update.sh

Pivotal ID # 179105055: Update Java Home PROD

---

commons/commons-serialization/build.gradle.kts
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/FileListTsvStreamDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializationErrorsTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvSingleElementDeserializationTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvToStringSerializerTest.kt
commons/commons-transpiler/src/test/kotlin/ac/uk/ebi/transpiler/factory/FilesTableTemplateFactory.kt
commons/commons-tsv-util/build.gradle.kts
commons/commons-tsv-util/src/main/kotlin/ebi/ac/uk/dsl/tsv/TsvDsl.kt
commons/commons-tsv-util/src/test/kotlin/ebi/ac/uk/dsl/tsv/TsvDslTest.kt
commons/commons-util/build.gradle.kts
commons/commons-util/src/test/kotlin/ebi/ac/uk/util/file/ExcelReaderTest.kt
settings.gradle
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/query/ProjectsListTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ExtCollectionSubmitTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToCollectionsTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/web/handlers/StatsFileHandlerTest.kt

https://www.pivotaltracker.com/story/show/179144369

Pivotal #ID 179144369: Add tsv library

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt

https://www.pivotaltracker.com/story/show/178974842
Add the section title to the text search index for both, submissions and submission requests

Pivotal ID # 178974842: Section Title Index

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/ActivateByEmailRequest.kt
docs/api/BioStudiesInternalAPI.yaml
docs/api/security/ActivateUserByEmail.yaml
docs/api/security/SetUpPassword.yaml
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityQueryServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/test/SecurityTestEntities.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/util/SecurityUtilTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt

https://www.pivotaltracker.com/story/show/179055347
- Update the activation workflow to activate and set up the new password as a transactional operation

Pivotal ID # 179055347: Update AE Activation Email

---

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt

https://www.pivotaltracker.com/story/show/179450300
- Fix submission expiration SQL query
- Add resubmission to the delete submission integration test

Pivotal ID # 179435581: Deleting Submissions Isn't Working

---

.gitlab-ci.yml
ci/bio-commandline.yml

https://www.pivotaltracker.com/story/show/179040289
Setup deployment per environment for the BioStudies CLI

Pivotal ID # 179040289: BioStudies CLI Deployment

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionRequestMessage.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFileProcessingConfigExt.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFileProcessingConfigExt.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/request/FileProcessingConfig.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/FileSystemService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/nfs/FileProcessingConfigTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/FileSystemServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/SubmissionRequest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt

- Adjust the submitter log messages format in order to be identified by Kibana
- Include the AccNo and Owner in each message so they can be properly indexed
- Adjust tests

Pivotal ID # 179436227: Improve Logs Messages 

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/MongoDbConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/from/DocFileListDocFileConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/FileListDocFileConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocFile.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFile.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/from/DocFileListDocFileConverterTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/FileListDocFileConverterTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocSubmissionTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt

https://www.pivotaltracker.com/story/show/180124164

Pivotal ID # 180124164: Re use ext mapping for file list

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/chunks/TsvChunkGenerator.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt

https://www.pivotaltracker.com/story/show/179867189
- Fix regular expression to detect values inside quotes
- Add the corresponding test case

Pivotal ID # 179867189: TSV Quotes Deserialization

---

.gitlab-ci.yml
ci/update.sh
submission/submission-webapp/gradle.properties

https://www.pivotaltracker.com/story/show/179939266
Get the process id for specific application path

Pivotal ID # 179939266: SpringBoot Admin App Registration

---

commons/commons-model-extended/gradle.properties
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensions.kt
commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtSectionExtensionsTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFtpService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/fire/FireFtpServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/validator/collection/EuToxRiskValidator.kt

https://www.pivotaltracker.com/story/show/179921481

Pivotal ID #179921481: Fire ftp publishing

---

.gitignore
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/constants/ExtSerializationFields.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtSubmissionSerializer.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/serializers/ExtSubmissionSerializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationServiceTest.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
commons/commons-test/src/main/kotlin/ebi/ac/uk/test/ExtSubmissionFactory.kt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtNotificationServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/ExtSubmissionFactory.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/from/DocSubmissionConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/SubmissionConverter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocSubmission.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSubmissionMapper.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionModel.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/from/DocSubmissionConverterTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/to/SubmissionConverterTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocSubmissionTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/SubmissionTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/doc/SubmissionDocTestHelper.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/test/doc/ext/ExtSubmissionFactory.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/to/ToExtSubmissionMapper.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/test/SubmissionTestHelper.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/180253535

Pivotal ID #180253535: Submission storage mode

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionExt.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt

https://www.pivotaltracker.com/story/show/180363408
Include inner sections for the referenced files

Pivotal ID # 180363408: Inner Section File List Referenced Files

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/persistence/UserDataRepositoryExt.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt

https://www.pivotaltracker.com/story/show/180282390

Pivotal ID # 180282390: Reset password should activate user

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSectionExtensions.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensions.kt
commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtSectionExtensionsTest.kt
commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensionsTest.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/base/StringExt.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/base/StringExtTest.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/model/NotificationTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SubmissionReleaseTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SuccessfulSubmissionTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtNotificationService.kt
submission/notifications/src/main/resources/templates/release-notification.txt
submission/notifications/src/main/resources/templates/successful-resubmission.txt
submission/notifications/src/main/resources/templates/successful-submission.txt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtNotificationServiceTest.kt

https://www.pivotaltracker.com/story/show/180345449

Pivotal #ID 180345449: handle empty title submission email notification

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/FileListSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/validation/Errors.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/FileListSerializerTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/ValidationExceptionHandler.kt

https://www.pivotaltracker.com/story/show/180152694
- Improve file list validation error messages
- Add handler to return the corresponding status code

Pivotal ID # 180152694: File List Validation

---

commons/commons-test/src/main/kotlin/ebi/ac/uk/test/TemporaryFolderExt.kt
commons/commons-util/build.gradle.kts
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/HardLinkFileVisitor.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpService.kt
submission/persistence-mongo/build.gradle.kts
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/ExtSubmissionRepository.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityQueryService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/JmsConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResource.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/179040289

Pivotal ID #179040289: Mongo Migration PROD

---

commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/slack/SystemNotification.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/FailedSubmissionRequestMessage.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionRequestMessage.kt
infrastructure/src/main/resources/setup/mysql/Schema.sql
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/request/SubmissionRequest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionRequest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SqlSubmissionRequestService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SubmissionSqlPersistenceService.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSubmissionRequest.kt
submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt
submission/submission-webapp/gradle.properties
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/SubmitRequest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt

https://www.pivotaltracker.com/story/show/180656091

Pivotal Id #180656091: Submission request should store all request information

---

ci/update.sh
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializer.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/FireExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/GeneralExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/SecurityExceptionWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/SerializationExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/exception/ValidationExceptionHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResource.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt

https://www.pivotaltracker.com/story/show/180929480

Pivotal ID # 180929480: Allow submission request to be manually re trigger

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt

https://www.pivotaltracker.com/story/show/180957544

Pivotal ID # 180957544: Re processing submissions is failing

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt

https://www.pivotaltracker.com/story/show/180962335

Pivotal ID # 180962335: Only pending to process request need to be proccesed

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/api/RtClient.kt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/api/RtClientTest.kt

Change RT ticket status to resolved upon submission
[Delivers #180853446]

Pivotal ID #180853446: Change RT ticket status upon submission

---

commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFile.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileList.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt

https://www.pivotaltracker.com/story/show/181024221

Pivotal ID # 181024221: Md5 should be calculated after accepting submission

---

infrastructure/src/main/resources/setup/mysql/Dockerfile.test
infrastructure/src/main/resources/setup/mysql/Projects.sql
infrastructure/src/main/resources/setup/mysql/Schema.sql

https://www.pivotaltracker.com/story/show/181032586

Remove submission-related changes from mysql set-up

---

commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFile.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileList.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileListTest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt

https://www.pivotaltracker.com/story/show/181031416

Pivotal ID # 181031416: Files size should be calculated after accepting submission

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/NotificationConfig.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/model/NotificationTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SubmissionReleaseTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SuccessfulSubmissionTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtNotificationService.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtTicketService.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/SecurityNotificationService.kt
submission/notifications/src/main/resources/templates/release-notification.txt
submission/notifications/src/main/resources/templates/successful-resubmission.txt
submission/notifications/src/main/resources/templates/successful-submission.txt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtNotificationServiceTest.kt

https://www.pivotaltracker.com/story/show/181142221

Pivotal ID # 181142221: Emails formating issues

---

events/events-publisher/src/main/kotlin/uk/ac/ebi/events/config/EventsPublisherConfig.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt

https://www.pivotaltracker.com/story/show/181155613

Pivotal ID # 181155613: Add push to partial updates exchange on study refresh

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/MongoDbConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/ExternalConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbReposConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionStatsDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/ExtSubmissionRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/StatsMongoDataServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoMetaQueryServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/PersistenceConfig.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/data/UserDataConfig.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/181206866

Pivotal ID # 181206866 Remove application property enableMongo

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Attributable.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Attribute.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/TableModel.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/AttributeExt.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/Functions.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionModel.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/model/SubmitWebRequest.kt

Add support for empty values in detail attributes

Pivotal ID # 180481465: Empty Attribute Value Handling

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/builders/FileBuilder.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/integration/SerializationService.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/FileJsonDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/TsvSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/model/TsvChunk.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FileListTsvStreamDeserializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/XmlSerializer.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/deserializer/FileStandaloneXmlDeserializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileListJsonStreamDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/FileListTsvStreamDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializationErrorsTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/FileListXmlStreamDeserializerTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/deserializer/FileStandaloneXmlDeserializerTest.kt

Make the path required for file entries in page tab

Pivotal ID # 181330654: File List Empty Path Entries

---

scheduler/exporter-task/src/main/kotlin/uk/ac/ebi/scheduler/exporter/service/PublicOnlyExporterService.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/exporter/domain/ExporterTrigger.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/scheduling/DailyScheduler.kt
submission/submission-webapp/src/main/resources/application-local.yml
submission/submission-webapp/src/main/resources/application.yml

- Fix exporter jobs logging
- Improve jobs scheduling
- Create json writer only when necessary

Pivotal ID # 180640412: PMC Links Exporter

---

submission/notifications/src/main/resources/templates/activation.html
submission/notifications/src/main/resources/templates/reset-password.html

https://www.pivotaltracker.com/story/show/180582617
Display link text in html based e-mails

Pivotal ID # 180582617: Change Password Reset Email Text

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/api/RtClient.kt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/api/RtClientTest.kt

https://www.pivotaltracker.com/story/show/181651255
Set the RT ticket status to "Resolved" when there's a resubmission

Pivotal ID # 181651255: Set RT ticket To Resolved When Resubmitting

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/exception/InvalidFileListException.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/FileListSerializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/FileListSerializerTest.kt

https://www.pivotaltracker.com/story/show/181651670
Handle the escenario where a directory is used as a file list

Pivotal ID # 181651670: Error Message Displays Full Path

---

buildSrc/src/main/kotlin/Dependencies.kt

https://www.pivotaltracker.com/story/show/181752675
Upgrade spring version to avoid a vulnerability reported by Spring

Pivotal ID # 181752675: Spring Vulnerability

---

submission/submission-webapp/gradle.properties
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/FireMockDatabase.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/TestWireMockTransformer.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/handlers/PathDownloadHandler.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/handlers/QueryHandlers.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/handlers/SaveMetadataHandler.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/helpers/FireFilesSource.kt

https://www.pivotaltracker.com/story/show/181328889
- Add base path to the FIRE files source
- Add integration test for reusing previous versions file list and referenced files

Pivotal ID # 181328889: File List Extension Is Overwritten

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFile.kt

Missing direct use of the ExtFileType enum

Pivotal ID # 181597483: FIRE Directories Persistence

---

.gitlab-ci.yml
ci/bio-commandline.yml
ci/submission-handlers.yml
ci/submitter.yml
deploy.gradle

https://www.pivotaltracker.com/story/show/181028528
- Move beta deployment to HL
- Include deployment for the instance used for AE migration
- Set up automatic deployment for beta branch

Pivotal ID # 181028528: Migrate backend to HL

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/ValidateFileListCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Parameters.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/ValidateFileListRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/ValidateFileListCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt

**Title**: Pivotal ID # 181559436: Develop a simple (internal) tool for file list checking so that we could easily help users when they have file list troubles.
**Pivotal Link:** https://www.pivotaltracker.com/story/show/181559436
Please include a list of the changes:
* Adds new command `ValidateFileListCommand`
* Adds the new command to the BioStudies Command Line
* Tweaks the `SubmissionService` and the `SubmissionClient` for making file list validation requests

Pivotal ID # 181559436: Add support for validating file list through bio CLI.

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/BioWebClient.kt
commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtFileTest.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/common/SerializationConfig.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/common/TsvPagetabExtension.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/ext/FileExtensions.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/NfsPageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabUtil.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/fire/FireFilesServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/nfs/NfsFileProcessingConfigTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/pagetab/NfsPageTabServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileListMapperTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtSubmissionMapperTest.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/182178027

Pivotal ID # 182178027: Improve processing logs

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/MigrationRequest.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceMigrationTest.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/ExtSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt
client/bio-webclient/src/test/kotlin/ac/uk/ebi/biostd/client/api/ExtSubmissionClientTest.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializer.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationService.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializerTest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/exception/SecurityException.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResourceTest.kt

https://www.pivotaltracker.com/story/show/182273948

Pivotal ID # 182273948: Command line migration command

---

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/RetryWebClient.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFile.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileListMapper.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSectionMapper.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtTable.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSectionMapperTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtTableTest.kt
commons/commons-model-extended-serialization/gradle.properties
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/FileProcessingService.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/util/collections/EitherExtensions.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/util/collections/EitherExtensionsTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/FirePageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/NfsPageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/UpdatedSection.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/nfs/NfsFilesServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/pagetab/FirePageTabServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/pagetab/NfsPageTabServiceTest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/from/ToDocSectionMapper.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FileSystemConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/helpers/FireFilesSource.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoader.kt

https://www.pivotaltracker.com/story/show/182333701
- added default file type
- improving logging.

Pivotal ID # 182333701: Submissions stages

---

scheduler/exporter-task/src/main/resources/application.yml
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/exporter/api/ExporterProperties.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/exporter/domain/ExporterTrigger.kt
scheduler/scheduler/src/main/resources/application.yml
scheduler/scheduler/src/test/kotlin/uk/ac/ebi/scheduler/exporter/domain/ExporterTriggerTest.kt
scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/ExporterProperties.kt
scheduler/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/ExporterPropertiesTest.kt

https://www.pivotaltracker.com/story/show/182583027
Add missing property for the exporter application executed by the scheduler

Pivotal ID #182583027: PMC Export Empty Files

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionDraftClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/UserFilesClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/extensions/ResponseEntity.kt
commons/commons-model-extended/build.gradle.kts
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt
commons/commons-model-extended/src/testFixtures/kotlin/ebi/ac/uk/extended/model/createNfsFile.kt
commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/JsonSerializer.kt
submission/persistence-filesystem/build.gradle.kts
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesServiceTest.kt
submission/persistence-mongo/build.gradle.kts
submission/submission-webapp/build.gradle.kts
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/converters/ExtPageSubmissionConverter.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/converters/ExtSubmissionConverter.kt
submission/submitter/build.gradle.kts

https://www.pivotaltracker.com/story/show/182693604

Pivotal ID # 182693604: Qodana issues 

---

submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt

https://www.pivotaltracker.com/n/projects/1189310/stories/182793083
* Remove partial update queue for UI

Pivotal ID #182793083:  Remove partial update queue for UI

---

submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireService.kt

https://www.pivotaltracker.com/story/show/182758404
Fix file persistence priority

Pivotal ID # 182758404: Multiple File References

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/ReleaseRequest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionReleaser.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessor.kt

https://www.pivotaltracker.com/story/show/182853322

Pivotal ID # 182853322: Release submission include all files

---

infrastructure/src/main/resources/setup/mysql/SetUpDatabase.cmd
infrastructure/src/main/resources/setup/mysql/SetUpDatabase.sh
scheduler/scheduler/src/main/resources/application.yml
submission/submission-handlers/src/main/resources/application.yml
submission/submission-webapp/src/main/resources/application.yml

Update the BioAdmin URL to point to the HL servers

Pivotal ID # 182855983: Move BioAdmin HL

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitRequestBuilder.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionDraftResource.kt

- Add the draft key to the submission request
- Improve integration tests

Pivotal ID # 182829593: Drafts Are Not Being Deleted Upon Submission

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt

https://www.pivotaltracker.com/story/show/182829591
- Fix sort step in the submissions aggregation
- Remove grouping from the aggregation since it's no longer required
- Remove unused methods and properties
- Fix typos

Pivotal ID # 182829591: Submissions List Order

---

submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/PageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/FirePageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/NfsPageTabService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/FileSystemService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/fire/FireFtpServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/nfs/NfsFtpServiceTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/FileSystemServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FileSystemConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/FtpResource.kt
submission/submission-webapp/src/main/resources/application.yml
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ext/ExtSubmissionServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionReleaser.kt

https://www.pivotaltracker.com/story/show/182987585

Pivotal ID # 182987585: Per submission storage mode

---

scheduler/common/cluster-client/build.gradle.kts
scheduler/common/cluster-client/src/main/kotlin/ac/uk/ebi/cluster/client/lsf/ClusterOperations.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/config/SchedulerConfig.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/properties/SshProperties.kt
scheduler/scheduler/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/183046110

Pivotal ID # 183046110: Scheduler sch config

---

buildSrc/src/main/kotlin/Dependencies.kt
scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/common/JavaAppProperties.kt
scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/SubmissionReleaserProperties.kt
scheduler/tasks/submission-releaser-task/build.gradle.kts
submission/persistence-common-api/build.gradle.kts

https://www.pivotaltracker.com/story/show/183058373
- removed unecesary dependencies confusing spring boot and making it fail due a missing sql datasource.

Pivotal ID # 183058373: Releaser not running

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/WebSubmissionDraft.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/JmsConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/183046342

Pivotal ID # 183046342: Submitter configurable concurrency

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/RequestStatus.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionQueryService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt

https://www.pivotaltracker.com/story/show/183351718
- Validate the request processed status including all the submission stages
- Normalize methods naming

Pivotal ID # 183351718: Active Requests Not Showing On Submissions List

---

scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/properties/AppProperties.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/scheduling/DailyScheduler.kt
scheduler/scheduler/src/main/resources/application.yml
scheduler/tasks/exporter-task/build.gradle.kts

https://www.pivotaltracker.com/story/show/183393317
- Add separated properties for the PMC import/export tasks
- Remove unnecessary JPA dependency in the exporter task

Pivotal # 183393317: Separate PMC Export/Import Schedule

---

scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/service/SubmissionReleaserService.kt
scheduler/tasks/submission-releaser-task/src/test/kotlin/uk/ac/ebi/scheduler/releaser/service/SubmissionReleaserServiceTest.kt

Pivotal ID # 183476590: Push message to MQ on release

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationServiceExt.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/RequestStatus.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionRequest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FilePersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleaner.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoader.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaser.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleanerTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoaderTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessorTest.kt

https://www.pivotaltracker.com/story/show/183324114
- Track current processed file
- Remove page tab operation from storage service since it's a separate concern

Pivotal ID # 183324114: Decouple Request Files - Track Current File

---

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireClientFactory.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionRequest.kt

https://www.pivotaltracker.com/story/show/183559025

Pivotal ID # 183559025: Retry when can not access FIRE

---

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt

[Delivers #182878880] Push delete message to RabbitMQ

Pivotal ID # 183476590: Push message to MQ on delete

---

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/FireApiFile.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensions.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt

https://www.pivotaltracker.com/story/show/183448558

Pivotal ID # 183448558: Allow Fire Bypassing

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionDraftPersistenceService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionDraft.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoPersistenceServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionDraftResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt

https://www.pivotaltracker.com/story/show/183578315
- Introduced new state for draft so they are not deleted on submission

Pivotal ID # 183578315: Submitted draft should not be deleted

---

commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToFile.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToFileTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionStagesHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitterTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestIndexer.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoader.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessor.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoaderTest.kt

https://www.pivotaltracker.com/story/show/183557519
Rollback the changes related to adding the MD5 to the pagetab files

Pivotal ID # 183557519: Rollback Pagetab MD5 Feature 

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/FileSourcesList.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/FilesSource.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/io/sources/FilesListSource.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/io/sources/PathSource.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensions.kt
commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensionsTest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/SingleFieldDtos.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/SubmissionProjects.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListValidationTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/GeneralConfig.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactory.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/FireFilesSource.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/SubmissionFilesSource.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/FileSourcesService.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactoryTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/helpers/FireFilesSourceFactoryTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/FileSourcesServiceTest.kt

https://www.pivotaltracker.com/story/show/183389588
- Fix relPath query
- Add the logic to bypass the fire validation in the submission source
- Add the corresponding source based on the submission storage mode
- Remove unnecessary parameter in the file source api

Pivotal ID # 183389588: Files Source For Metadata Updates

---

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/api/FireWebClient.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireClient.kt
client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/RetryWebClient.kt
client/fire-webclient/src/test/kotlin/uk/ac/ebi/fire/client/api/FireWebClientTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFtpServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/FireMockDatabase.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/handlers/PublishHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaser.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaserTest.kt

https://www.pivotaltracker.com/story/show/183804838
- updated release job to reflect FIRE response

Pivotal ID # 183804838: publish files resumable support

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/FileProcessingService.kt
commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/RequestCreated.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SubmissionRequest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionAsyncTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionStagesHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionStagesHandlerTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitterTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/ExtSubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaser.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestSaver.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessorTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaserTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestSaverTest.kt

https://www.pivotaltracker.com/story/show/183909764

Pivotal ID # 183909764: Submission save stage

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/TsvChunkExt.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt

https://www.pivotaltracker.com/story/show/183499288
Fix empty section accNo deserialization in TSV

Pivotal ID # 183499288: TSV Multiple Empty Subsection AccNo

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SubmissionReleaseTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/integration/templates/SuccessfulSubmissionTemplate.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtNotificationService.kt
submission/notifications/src/main/resources/templates/release/Default.txt
submission/notifications/src/main/resources/templates/submission/ArrayExpress.txt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/service/RtNotificationServiceTest.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/NotificationProperties.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/main/resources/application.yml
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt

https://www.pivotaltracker.com/story/show/183512371
- Add a property to specify the ST url
- Include the collection specific URL to the notifications
- Simplify the login in the notifications listener class

Pivotal ID # 183512371: Update Emails With A Collection Specific URL

---

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbCounter.kt
submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SqlPersistenceServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToCollectionsTest.kt

https://www.pivotaltracker.com/story/show/183944271
Start the new accNo sequences with 1 instead of 0

Pivotal ID # 183944271: First Collection Submission AccNo

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt

Configure referenced files cursor timeout and limit

Pivotal ID # 184014407: Multiple Reference Files In Resubmission

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/UserFilesClient.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/184045759
* hard link creation fixed and add tests
* user files web client improvements

Pivotal ID # 184045759: Attached folders not correctly published in nfs ftp

---

docs/api/BioStudiesPublicAPI.yaml

https://www.pivotaltracker.com/story/show/183628268
Fix server urls

Pivotal # 183628268: Improve Backend Docs

---

scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/persistence/ReleaserRepository.kt
scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/service/SubmissionReleaserService.kt

https://www.pivotaltracker.com/story/show/184149873

Pivotal ID # 184149873: Releaser should not fail on a single submission fail

---

docs/api/BioStudiesInternalAPI.yaml
docs/api/BioStudiesPublicAPI.yaml
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt

https://www.pivotaltracker.com/story/show/183911659
Delete a public submission as a superuser-only operation

Pivotal ID # 183911659: Delete Public Submission

---

submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt

https://www.pivotaltracker.com/story/show/183391039
Fix new version calculation to consider deleted versions

Pivotal ID # 183391039: Validate Already Existing Request Versions

---

submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/LogSubmissionListener.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionStagesHandler.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionStagesHandlerTest.kt

https://www.pivotaltracker.com/story/show/184278951
Remove duplicated message publishing

Pivotal ID # 184278951: Publishing Message Is Being Sent Twice

---

.gitlab-ci.yml
ci/docker.yml
ci/submitter.yml
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabService.kt
submission/submission-webapp/Dockerfile
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/SubmissionWebApp.kt

https://www.pivotaltracker.com/story/show/184246638
Please include a list of the changes:
* add GitLab job to build and push submitter docker image

Pivotal ID # 184246638: Backend docker image

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/exception/ConcurrentSubException.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequestModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepositoryTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/ConcurrentSubException.kt

https://www.pivotaltracker.com/story/show/184213416

Pivotal ID # 184213416: Upsert Submission Request Creation

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationServiceExt.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestIndexer.kt

https://www.pivotaltracker.com/story/show/184191732

Pivotal ID # 184191732: Prioritize Pagetab files processing

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/FileListDocFileDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbReposConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/FileListDocFileRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionQueryService.kt
submission/submission-webapp/src/main/resources/application.yml
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ext/ExtSubmissionPersistenceQueryServiceTest.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactory.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/SubmissionFilesSource.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactoryTest.kt

https://www.pivotaltracker.com/story/show/184364448

Pivotal ID # 184364448: Previos version file check taking longer than expected

---

ci/update.sh

https://www.pivotaltracker.com/story/show/183070739
Preserve current logs on application start up

Pivotal ID # 183070739: Fix Backend Log Rotation

---

submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/184541319

Pivotal ID # 184541319: SubBasePath property null by default

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceServiceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/RetryHandler.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoader.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessor.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaser.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoaderTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestProcessorTest.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestReleaserTest.kt

https://www.pivotaltracker.com/n/projects/1189310/stories/184548479

Pivotal ID # 184548479: Mongo database hit optimization

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FileListTsvStreamDeserializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/FileListTsvStreamDeserializerTest.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/ext/FileExtensions.kt

https://www.pivotaltracker.com/story/show/184661954

Pivotal ID # 184661954: File list empty lines should be ignored

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/events/SubmissionMessage.kt
events/events-publisher/build.gradle.kts
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/config/EventsPublisherConfig.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/SubmissionReleaserApp.kt
scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/config/ApplicationConfig.kt
scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/service/EventsPublisherService.kt
scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/service/SubmissionReleaserService.kt
scheduler/tasks/submission-releaser-task/src/test/kotlin/uk/ac/ebi/scheduler/releaser/service/EventsPublisherServiceTest.kt
scheduler/tasks/submission-releaser-task/src/test/kotlin/uk/ac/ebi/scheduler/releaser/service/SubmissionReleaserServiceTest.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/events/Events.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/QueuesConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListenerTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/JmsConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt

https://www.pivotaltracker.com/story/show/184753484

Pivotal ID # 184753484: Support multiple backends

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializer.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/EitherExtTypeDeserializerTest.kt
commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializerTest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FilePersistenceConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleaner.kt
submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoader.kt
submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestLoaderTest.kt

https://www.pivotaltracker.com/story/show/184773765

Pivotal ID # 184773765: Fire directory submission can not be re submitted

---

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionRefreshApiTest.kt

Fix broken test with release date in the past

Pivotal # 182595703: Submission Releasing Workflow

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/MongoDbReactiveConfig.kt

Pivotal ID # 185788503: Reactive Mongo

---

submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoader.kt
submission/submission-webapp/src/itest/resources/application.yml
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/internal/ApplicationConfig.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/186399181

Pivotal ID # 186399181: Retry system properties

---

submission/notifications/src/main/resources/templates/release/BioImages.txt
submission/notifications/src/main/resources/templates/resubmission/BioImages.txt
submission/notifications/src/main/resources/templates/submission/BioImages.txt

https://www.pivotaltracker.com/story/show/186281758
Add e-mail notification templates for the BioImages collection

Pivotal ID # 186281758: BioImages E-Mail Notifications

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt

https://www.pivotaltracker.com/story/show/186529137

Pivotal ID # 186529137: Extend cursor timeout

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt

https://www.pivotaltracker.com/story/show/186496317
Close input stream for listing files

Pivotal ID # 186496317: Too Many Open Files

---

submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/model/DoiRequest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/service/DoiService.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/service/DoiServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/184977702
- Fix ORCID in the DOI request
- Make the notifications e-mail configurable

Pivotal ID # 184977702: Assign DOIs Automatically

---

client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FtpClientExt.kt
client/ftp-webclient/src/test/kotlin/ebi/ac/uk/ftp/FtpClientExtTest.kt
submission/file-sources/build.gradle.kts
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/builder/NfsFileBuilder.kt
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/sources/FtpSource.kt

https://www.pivotaltracker.com/n/projects/1189310
- added file size calculation

Pivotal ID # 186655077: FTP calculate file size

---

scheduler/tasks/submission-releaser-task/src/main/kotlin/uk/ac/ebi/scheduler/releaser/config/ApplicationConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtSubmissionSubmitter.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/ApplicationConfig.kt
submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/exception/CustomErrorHandler.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/exception/CustomErrorHandlerTest.kt

https://www.pivotaltracker.com/story/show/186629008
- Add message converter to the rabbit template
- Configure custom exception handler to catch failing messages

Pivotal ID # 186629008: Slack Message For Failed Notifications

---

client/ftp-webclient/build.gradle.kts
client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/SimpleFtpClient.kt
client/ftp-webclient/src/test/kotlin/ebi/ac/uk/ftp/FtpClientTest.kt
commons/commons-test/src/main/kotlin/ebi/ac/uk/test/TemporaryFolderExt.kt

https://www.pivotaltracker.com/story/show/186638811
- improved FTP test

Pivotal ID # 186638811: Improve FTP Test

---

client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FTPClientPool.kt
client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FtpClient.kt
client/ftp-webclient/src/test/kotlin/ebi/ac/uk/ftp/FtpClientTest.kt
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/sources/FtpSource.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/SecurityProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/ProfileService.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/186768872
- Add a property for the ftp root path
- Simplify FTP source logic
- Fix typos

Pivotal ID # 186768872: Input FTP Folder Permission Structure Review

---

client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FTPClientPool.kt

https://www.pivotaltracker.com/story/show/186941052
- enabled test on borrow

Pivotal ID # 186941052: Check Ftp Connections Before Borrow

---

submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/api/RtClient.kt
submission/notifications/src/main/kotlin/ebi/ac/uk/notifications/service/RtTicketService.kt
submission/notifications/src/test/kotlin/ebi/ac/uk/notifications/api/RtClientTest.kt

https://www.pivotaltracker.com/story/show/186710912
Fix bcc for comments

Pivotal ID # 186710912: BCC-ing All E-mail Notifications

---

submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/FilePersistenceConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/SubmitterConfig.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/WebConfig.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/186992651
- Move submission persistence related properties to the persistence
- Move fire temp dir property to the fire properties section
- Update the property names according to the new feature

Pivotal ID # 186992651: NFS Private Submissions Persistence

---

commons/commons-serialization/gradle.properties
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SubmissionRequest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequestModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceServiceTest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleaner.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestFinalizer.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestIndexer.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoader.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestProcessor.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestReleaser.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestSaver.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanerTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestIndexerTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoaderTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestProcessorTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestReleaserTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestSaverTest.kt

https://www.pivotaltracker.com/story/show/187221170
- extracted request processing logic

Pivotal ID # 187221170: Submission concurrency control

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/ExtSubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmitClient.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/util/date/OffsetDateTime.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionReleaseTest.kt
submission/submission-webapp/src/itest/resources/itestsInventory/itestsInventory.md
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResource.kt

https://www.pivotaltracker.com/story/show/187312138

Pivotal ID #187312138: Release endpoint

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/FileSourcesList.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/io/sources/FileSourcesListTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSectionMapperTest.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtTableTest.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/PageTabFileReaderTest.kt
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/builder/FilesSourceListBuilder.kt
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/config/FilesSourceConfig.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/exceptions/FilesProcessingExceptionTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/service/FileSourcesServiceTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/validator/filelist/FileListValidatorTest.kt
submission/submission-webapp/src/itest/resources/application_base.yml
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/187315490

Pivotal ID # 187315490: Check files path characters feature flag

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/paths/SubmissionFolderResolver.kt
commons/commons-bio/src/test/kotlin/ebi/ac/uk/paths/SubmissionFolderResolverTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionReleaseTest.kt

https://www.pivotaltracker.com/story/show/187312138

Pivotal ID # 187312138: Release endpoint

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SubmissionRequestFile.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanIndexer.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanIndexerTest.kt

https://www.pivotaltracker.com/story/show/187456681
- added request cleaner indexer

Pivotal ID # 187456681: Submission request file status

---

client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FTPClientPool.kt
client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FtpClient.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt

https://www.pivotaltracker.com/story/show/187635507
Handle hidden files

Pivotal ID # 187635507: FTPSource Directory Files

---

.gitlab-ci.yml
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
ci/update.sh
client/ftp-webclient/src/test/kotlin/ebi/ac/uk/ftp/FtpClientTest.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/PageTabServiceTest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/FilePersistenceConfig.kt
submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/exception/CustomErrorHandlerTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionWebConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/stats/domain/service/SubmissionStatsServiceTest.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftServiceTest.kt

https://www.pivotaltracker.com/story/show/187229373
- Updated to use Java 17

Pivotal ID # 187229373: Backend using Java 17

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/RemoteClusterClient.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/coroutines/WaitUntil.kt
scheduler/tasks/submission-migrator-task/src/main/kotlin/uk/ac/ebi/scheduler/migrator/service/SubmissionMigratorService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtendedSubmissionSubmitter.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/stats/SubmissionStatsTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionAsyncTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionReleaseTestWithSecretKey.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionStorageModeTest.kt

https://www.pivotaltracker.com/story/show/187863294
- wait utility improvements

Pivotal ID # 187863294: Wait test utility

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestSaver.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtSubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtendedSubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/LocalExtSubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteExtSubmissionSubmitter.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/extended/LocalExtSubmissionSubmitterTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestSaverTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtendedSubmissionSubmitterTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtSubmissionResourceTest.kt

https://www.pivotaltracker.com/story/show/187879690
- changed flow to avoid syncrouns stage execution

Pivotal ID # 187879690: Redesyn sync submission workflow

---

submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanIndexerTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoaderTest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestReleaserTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/ResubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/185361632
Improve tests

Pivotal ID # 185361632: Avoid Files Modification On Public Studies

---

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/TransferCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/ValidateFileListCommand.kt
client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/MigrateCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/TransferCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/ValidateFileListCommandTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceMigrationTest.kt
client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmitClient.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/filelist/FileListValidationTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt

https://www.pivotaltracker.com/story/show/187815483
- async submissions operations client

Pivotal ID # 187815483: Async Web Client

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/RequestStatus.kt
submission/submission-webapp/src/itest/itestsInventory.md
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/ResubmissionApiTest.kt

https://www.pivotaltracker.com/story/show/188156440
- added invalid as a processing state

Pivotal ID # 188156440}: re submission when INVALID state

---

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/SecurityProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestValidator.kt
submission/submission-webapp/src/itest/itestsInventory.md
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeleteFilesPermissionTest.kt
submission/submission-webapp/src/itest/resources/application_base.yml
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/188131969
- updated to use document

Pivotal ID # 188131969: Archive submission request

---

ci/jobs.yml
ci/slurm_wrapper.sh
client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/SlurmClusterClient.kt
deploy.gradle
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/config/SchedulerConfig.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/properties/AppProperties.kt
scheduler/scheduler/src/main/resources/application.yml
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ClusterProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/187642945
- Create a wrapper to execute commands in the cluster
- Use the job id to provide the dynamic output path
- Add a new property to specify the wrapper script location

Pivotal ID # 187642945: Partition Cluster Jobs Logs Path

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/extensions/FilePermissionsExtensions.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpService.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/extensions/FilePermissionsExtensionsTest.kt
submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpServiceTest.kt

https://www.pivotaltracker.com/story/show/187229710
Adjust permissions for FTP out

Pivotal ID # 187229710: DEV/BETA Backend To FTP/Public

---

events/events-publisher/src/main/kotlin/uk/ac/ebi/events/config/EventsPublisherConfig.kt
events/events-publisher/src/main/kotlin/uk/ac/ebi/events/service/EventsPublisherService.kt
events/events-publisher/src/test/kotlin/uk/ac/ebi/events/service/EventsPublisherServiceTest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ClusterProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteExtSubmissionSubmitter.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/JmsListeningConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionMessageListener.kt
submission/submission-webapp/src/main/resources/application.yml

https://www.pivotaltracker.com/story/show/188317828
- Add a property to configure the submission tasks execution time in the cluster
- Add a property to enable/disable the submission error notifications

Pivotal ID # 188317828: Submission Configuration Properties

---

submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/model/DoiRequest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/service/DoiService.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/service/DoiServiceTest.kt

https://www.pivotaltracker.com/story/show/188311113
- Allow single name authors for DOI registration
- If a single name is provided, it will be used as surname

Pivotal ID # 188311113: Crossref "Contributor" Element Registration

---

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/ExtSerializationServiceExt.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanIndexer.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleanIndexerTest.kt

https://www.pivotaltracker.com/story/show/188462206
- used old submission to determinate pagetab file nature.

Pivotal ID # 188462206: Handle xml removed page tab files

---

submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/service/DoiService.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/service/DoiServiceTest.kt

https://www.pivotaltracker.com/story/show/188311113
- Handle blank spaces in author names
- Log the DOI request to have traceability

Pivotal ID # 188311113: Crossref "Contributor" Element Registration (#889)

---

commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFileListMapper.kt
commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToFileListMapper.kt
commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToFileListMapperTest.kt
commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/service/FileProcessingService.kt
commons/commons-serialization-util/src/main/kotlin/uk/ac/ebi/serialization/common/FilesResolver.kt
commons/commons-serialization-util/src/test/kotlin/uk/ac/ebi/serialization/common/FilesResolverTest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileListMapper.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/archive/ArchiveScheduler.kt

https://www.pivotaltracker.com/story/show/181219386
- Delete files in the request-files folder
- Create temp files for simple submission read in the system temp folder rather than the request folder

Pivotal ID # 181219386: Clean Submission Temp Files

---

submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/TaskProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteExtSubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteSubmitterExecutor.kt
submission/submission-task/src/main/kotlin/uk/ac/ebi/biostd/submission/SubmissionTaskApp.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionWebConfig.kt

https://www.pivotaltracker.com/n/projects/1189310
- extracted task remote executor to be able to execute other submitter task

Pivotal ID # 188522739: Submission stats include number of directories

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionDraftClient.kt
client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmitClient.kt
commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/WebSubmissionDraft.kt
commons/commons-http/src/main/kotlin/ebi/ac/uk/commons/http/ext/WebClientExtSync.kt
docs/api/drafts/model/BasicDraft.yaml
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SubmissionDraft.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionDraftPersistenceService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/DocSubmissionDraft.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionDraftMongoPersistenceServiceTest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionSubmitter.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionSubmitterTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionDraftListApiTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionDraftResource.kt
submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftServiceTest.kt

https://www.pivotaltracker.com/story/show/188526717
- Add modification date to the drafts
- Use readable timestamp as the draft key
- Use reactive web client for the draft operations

Pivotal ID # 188526717: Improve Drafts Timeline Structure

---

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SubmissionRequest.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/request/ExtSubmitRequest.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequestModel.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepositoryTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceServiceTest.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionProcessor.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/LocalExtSubmissionSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/model/SubmissionConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/model/SubmitRequest.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubmissionSubmitterTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionDraftApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitRequestBuilder.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt

https://www.pivotaltracker.com/story/show/184033688
Add missing fields to the request model: key, draft content, accNo, version and owner

Pivotal ID # 184033688: Async Validation Process

---

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/ext/BufferedReaderExtensions.kt
submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/StatsDataService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionStatsDataRepository.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/StatsMongoDataService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/stats/StatsFileHandler.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/stats/SubmissionStatsService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/stats/SubmissionStatsTest.kt

https://www.pivotaltracker.com/story/show/188804317
- refactor logic to filter stats on service layer

Pivotal ID # 188804317: Ignore Invalid Stats

---

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/UserFilesClient.kt
client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/FtpClient.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/io/KFiles.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/TaskProperties.kt
submission/submission-webapp/src/itest/itestsInventory.md
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/files/UserFileApiTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/UserFilesResource.kt

https://www.pivotaltracker.com/story/show/188904728
- changed ftp client to use binary file type

Pivotal ID # 188904728: Downloaded ftp binary files are corrupted

---

submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestIndexer.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt

https://www.pivotaltracker.com/story/show/188954230

Pivotal ID # 188954230: Duplicated files should be processed only once 

---

scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt
scheduler/common/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterPropertiesTest.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/pmc/importer/api/PmcImporterResource.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/pmc/importer/domain/PmcLoaderService.kt
scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/scheduling/DailyScheduler.kt
scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/PmcTaskExecutor.kt
scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteSubmitterExecutor.kt

https://www.pivotaltracker.com/story/show/188905914

Pivotal ID # 188905914: PMC pipeline debug enhacements

---

submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/SecurityConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/SubmissionConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/SubmitterConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionService.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestFilesValidator.kt
submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionServiceTest.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityModuleConfig.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/SecurityFilter.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/SecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SqlSecurityQueryService.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/web/SecurityFilter.kt
submission/submission-security/src/main/kotlin/ebi/ac/uk/security/web/SpringSecurityFilter.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SecurityServiceTest.kt
submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/SqlSecurityQueryServiceTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/SecurityTestService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/TestConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SecurityWebConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionWebConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/UserAdminResource.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/helpers/OnBehalfUtils.kt

https://www.pivotaltracker.com/story/show/188973319
- changed service to use security service interface

Pivotal ID # 188973319: File presence check stage

---

scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/domain/SubmissionService.kt
scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLog.kt
submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/migrations/DatabaseChangeLogTest.kt

https://www.pivotaltracker.com/story/show/189048268
- added missing indexes

Pivotal ID # 189048268: Index new submission request

---

ci/jobs.yml

https://embl.atlassian.net/browse/BIOSTD-237
- fixed beta

BIOSTD-237: New Ftp apps location

---

submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubFolderResolver.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt

https://embl.atlassian.net/browse/BIOSTD-21
- added public path

BIOSTD-21: FTP Out File Retrieval Support

---

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtFileExtensions.kt
submission/file-sources/src/main/kotlin/uk/ac/ebi/io/builder/NfsFileBuilder.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoader.kt

https://embl.atlassian.net/browse/BIOSTD-246
- added support for calculated md5 to avoids its recalculation

BIOSTD-246: Files Reprocessing For NFS Public Submissions

---

scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/persistence/domain/SubmissionService.kt

https://embl.atlassian.net/browse/BIOSTD-262
- added retry to submitted submissions

BIOSTD-262: Retry PMC submission

---

commons/commons-bio/src/main/kotlin/ebi/ac/uk/paths/SubmissionFolderResolver.kt
commons/commons-util/src/main/kotlin/ebi/ac/uk/coroutines/WaitUntil.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt
submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt
submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepository.kt
submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ApplicationProperties.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/StatsConfig.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submission/SubFolderResolver.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/stats/SubmissionStatsCalculator.kt
submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/stats/SubmissionStatsService.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/stats/SubmissionStatsTest.kt
submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListSubmittedTest.kt
submission/submission-webapp/src/main/resources/application.yml

https://embl.atlassian.net/browse/BIOSTD-270
- added page tab copy support

BIOSTD-270: Pagetab local copy

---

ci/jobs.yml
client/bio-commandline/build.gradle.kts

https://embl.atlassian.net/browse/BIOSTD-287
- Remove unnecessary dependency
- Add CLI deployment to codon location

BIOSTD-287: Fix CLI Verbose Errors

---

submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionWebConfig.kt

https://embl.atlassian.net/browse/BIOSTD-288
- changed bean

BIOSTD-288: Submission search improvements

---

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FileListTsvStreamDeserializer.kt
commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/FileListTsvStreamDeserializerTest.kt
submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionOperationsResource.kt

https://embl.atlassian.net/browse/BIOSTD-249
- fixed null value at the end of a table

BIOSTD-249: Handle null columns values excel file list
