EBIBioStudies/biostudies-backend-services

commons-bio/src/main/kotlin/ebi/ac/uk/model/File.kt, commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/FileExt.kt, scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/config/AppConfig.kt, scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/data/MongoDocService.kt, scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/data/MongoRepository.kt, scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/data/docs/SubmissionDoc.kt, scheduler/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt, scheduler/pmc-processor-task/src/main/resources/application.yml, scheduler/pmc-processor-task/src/test/kotlin/ac/uk/ebi/pmc/importer.data/MongoDocServiceTest.kt, scheduler/scheduler/src/main/kotlin/ac/uk/ebi/pmc/scheduler/pmc/importer/PmcImporterService.kt, scheduler/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt, serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/serializer/FileSerializer.kt, serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/SectionSerializerTest.kt, submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/FilesSource.kt
- Properly process the errors in submission to log the problem instead of failing all the process
- Add a property to indicate the source file that will be used to submit
- Add logic to process only the submissions for a specific resource file that haven't been submitted yet
- Mark the submission as submitted in the Mongo DB once the process is finished
- Fix XML serializer unit test
- Remove unnecessary code
=> PMC Submitter Not Imported Only

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSection.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSubmission.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Section.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/ExtendedSectionExt.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/ExtendedSubExt.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SectionExt.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/SubExt.kt, commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/extensions/SubExtTest.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/ChunkProcessor.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvDeserializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvSerializationContext.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/model/TsvChunk.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/TsvToStringSerializer.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandler.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesValidator.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/LibraryFilesHandler.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGenerator.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/ResourceFile.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandlerTest.kt
- Refactor submission model to use library file as a string element for simple model and as a LibraryFile object for the extended model
- Remove library file object from serialization since it's now an attribute
- Adjust unit tests
=> Section Extended

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSection.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSubmission.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/extensions/ExtendedSectionExt.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/SerializationService.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/JsonSerializer.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/service/SubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/MultipartSubmissionResource.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/SubmissionResource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/SubmissionSubmitter.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandler.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/LibraryFilesHandler.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/handlers/OutputFilesGenerator.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/handlers/FilesHandlerTest.kt
- Add support for library file in all formats
- Use the extended section instead of the regular section for persistence
- Remove hardcoded library file in TSV format
- Fix library file name in the submission generated files
=>  Library File Formats Support

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/LibraryFile.kt, infrastructure/src/main/resources/setup/database/Schema.sql, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionMapper.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/LibraryFile.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/Section.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt
- Changes to persist files referenced in library files
- Add parameter to the submission mapper to indicate whether or not to load the referenced files from the database
- Verify referenced files in the integration tests
=> Persist Referenced Files

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/ExtendedSection.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/Section.kt, commons/commons-bio/src/test/kotlin/ebi/ac/uk/dsl/SubDslTest.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/BuilderSecExtensions.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/TsvToStringSerializer.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/SubTestFactory.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/SimpleSubmissionTsvParserTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvToStringSerializerTest.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/SubmissionDbMapper.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/MultipartSubmissionApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt
- Add parent accession number when adding a subsection
- Add parent accession to the TSV serialization
- Remove unnecessary "loadRefFiles" flag
- Improve unit tests
=> Fix: Pivotal ID # 168286132 - TSV Parent Acc No

buildSrc/src/main/kotlin/Dependencies.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/File.kt, commons/commons-serialization/build.gradle, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/Constants.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/TsvDeserializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/chunks/ChunkProcessor.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/chunks/TsvChunkGenerator.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/model/TsvChunkLine.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FileListTsvStreamDeserializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FilesTableTsvStreamDeserializer.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/test/TsvTestFactory.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvDeserializerTest.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/exception/SerializationExceptionHandlerTest.kt
https://www.pivotaltracker.com/story/show/168424987
- added multiple line support
- added specialized TsvChunkGenerator for chunks generation from pagetav content
=> Pivotal-168424987: Add-support-for-multiline-values-in-tsv-formating

commons/commons-bio/gradle.properties, commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/dto/SubmissionDto.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/util/SubmissionFilter.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/util/SubmissionFilterSpecification.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/SubmissionListApiTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionResource.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmissionWebHandlerTest.kt
- Return model instead of persistence object in submissions repository
- Change filters to OffsetDate
- Remove unnecessary headers
- Add version in response
- Update the tests and add an integration test to the filtering by release date
=> Pivotal ID # 168727325: Submission API

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/common/Functions.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvSingleElementDeserializationTest.kt, commons/commons-util/src/main/kotlin/ebi/ac/uk/util/file/PoiExt.kt, commons/commons-util/src/test/kotlin/ebi/ac/uk/util/file/ExcelReaderTest.kt
https://www.pivotaltracker.com/story/show/173361277
- Process empty excel cells
- Allow empty values in table attributes
=> Pivotal ID # 173361277: Excel File List Empty Attributes

submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/SubmissionNotFoundException.kt, submission/stats/src/main/kotlin/uk/ac/ebi/stats/service/SubmissionStatsService.kt, submission/stats/src/test/kotlin/uk/ac/ebi/stats/service/SubmissionStatsServiceTest.kt
https://www.pivotaltracker.com/story/show/173611760
- Ignore accessions that don't exist instead of failing
- Make the stats endpoints case insensitive
=> Pivotal ID # 173611760: Improve Stats AccNo Handling

client/bio-commandline/src/test/kotlin/ebi/ac/uk/paths/SubmissionFolderResolverTest.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/paths/SubmissionFolderResolver.kt, commons/commons-bio/src/test/kotlin/ebi/ac/uk/model/paths/FolderResolverTest.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FileSystemService.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FtpFilesService.kt, submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FilesServiceTest.kt, submission/persistence/src/test/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FtpFilesServiceTest.kt, submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/SecurityProperties.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/assertions/AllInOneSubmissionHelper.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/BaseIntegrationTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneMultipartFileSubmissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneSubmissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt, submission/submission-webapp/src/itest/resources/application.yml, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/GeneralConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/property/ApplicationProperties.kt, submission/submission-webapp/src/main/resources/application-local.yml, submission/submission-webapp/src/main/resources/application.yml
https://www.pivotaltracker.com/story/show/173792650
=> pivotal-173792650: Replace base path for multiple absolute paths 

commons/commons-util/src/main/kotlin/ebi/ac/uk/dsl/excel/ExcelSheet.kt, commons/commons-util/src/main/kotlin/ebi/ac/uk/util/file/PoiExt.kt, commons/commons-util/src/test/kotlin/ebi/ac/uk/util/file/ExcelReaderTest.kt
https://www.pivotaltracker.com/story/show/173569202
Improve excel reader:
- When all the cells in a row are empty, this will be interpreted as an empty line
- Remove empty elements from the end of a row
- Remove all empty rows starting at the last populated
- Add unit tests for these edge cases
Fixes # 173569202
=> Pivotal ID # 173569202: Empty Section Parent Cell

submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/util/AccNoPatternUtil.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/util/AccNoPatternUtilTest.kt
https://www.pivotaltracker.com/story/show/173457302
In an accession with several number groups only the last will be used
Fixes # 173457302
=> Pivotal ID # 173457302: RelPath Calculation

submission/persistence/build.gradle.kts, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbFiels.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSection.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/model/DbSubmission.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/LockExecutor.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/SubmissionRepository.kt, submission/persistence/src/main/kotlin/ac/uk/ebi/biostd/persistence/service/filesystem/FilesService.kt, submission/submission-security/src/test/kotlin/ebi/ac/uk/security/test/SecurityTestEntities.kt, submission/submission-webapp/build.gradle.kts, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/assertions/AllInOneSubmissionHelper.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/refresh/SubmissionApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToProjectsTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/PersistenceConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
https://www.pivotaltracker.com/story/show/174275642
=> Pivotal #ID 174275642: Submission loading strategy

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/project/submit/ProjectSubmitTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/exceptions/ProjectExceptions.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ProjectInfoService.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/ProjectInfoServiceTest.kt
https://www.pivotaltracker.com/story/show/174316468
- Fix validation errors on project AccNo template
- Improve class readability
- Add unit tests
Fixes # 174316468
=> Pivotal ID # 174316468: Project Refresh AccNo Template Validation

submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/BasicProject.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/BasicSubmission.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/model/SimpleSubmission.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/ProjectDataService.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/ProjectNotFoundException.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/config/SqlPersistenceConfig.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/integration/services/SubmissionSqlQueryService.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/Repositories.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/ProjectSqlDataService.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt, submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt, submission/submission-security/src/test/kotlin/ebi/ac/uk/security/service/UserPrivilegesServiceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/refresh/SubmissionRefreshApiTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmitterConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionResource.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionServiceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ParentInfoService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/ProjectInfoService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/TimesService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/ParentInfoServiceTest.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/ProjectInfoServiceTest.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/TimesServiceTest.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitterTest.kt
https://www.pivotaltracker.com/story/show/175163839
- Simplify SubmissionOperations interface and implementation
- Adjust services that used these queries in order to avoid multiple DB requests
- Adjust tests
- Rename SimpleSubmission to BasicSubmission in order to preserve the same terms all over the code
=> Pivotal # 175163839: Submission Operations Refactor

submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/exception/UserNotFoundException.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/from/ToDbSubmissionMapper.kt, submission/persistence-sql/src/test/kotlin/ac/uk/ebi/biostd/persistence/mapping/extended/from/ToDbSubmissionMapperTest.kt
Validate the submitter/owner exists when mapping an extended submission
=> Pivotal ID # 175780531: Ext Submission Submitter Validation

commons/commons-serialization-util/src/main/kotlin/uk/ac/ebi/serialization/extensions/JsonNode.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeJsonDeserializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/exception/NoAttributeValueException.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/AttributeDeserializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/FileDeserializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/LinkDeserializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/deserialization/SectionDeserializerTest.kt
https://www.pivotaltracker.com/story/show/176052254
- Validate attribute values in JSON deserialization
- Fix typo
=> Pivotal ID # 176052254: JSON Submission Attributes Validation

commons/commons-model-extended-serialization/src/main/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializer.kt, commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/EitherExtTypeDeserializerTest.kt, commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFileDeserializerTest.kt, commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtFilesTableDeserializerTest.kt, commons/commons-model-extended-serialization/src/test/kotlin/uk/ac/ebi/extended/serialization/deserializers/ExtSectionDeserializerTest.kt
https://www.pivotaltracker.com/story/show/176052264
Use path for ExtFile deserialization in order to honor the inner folders
=> Pivotal ID # 176052264: Inner Folder Mapping

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SecurityWebClient.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/api/security/CheckUserRequest.kt, submission/submission-security/src/main/kotlin/ebi/ac/uk/security/integration/components/ISecurityService.kt, submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/SecurityService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/security/web/SecurityResource.kt
https://www.pivotaltracker.com/story/show/176168841
=> Pivotal-176168841: Allow to check inactive user registration

commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSection.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToSection.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToSubmission.kt, commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/from/ToExtSectionTest.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/serialization/SectionJsonSerializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/serialization/TsvToStringSerializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/xml/serializer/SectionSerializer.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/JsonSerializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/serialization/SectionJsonSerializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/TsvToStringSerializerTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/xml/serializer/SectionSerializerTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/helpers/SourceGenerator.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/handlers/SubmitWebHandler.kt, submission/submission-webapp/src/main/resources/application.yml, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
https://www.pivotaltracker.com/story/show/176377632
- Include the file list extension in the serialization according to the format
- Include the submission folder as source for the submission files
=> Pivotal ID # 176377632: File list extension is missing in BIA studies

submission/notifications/src/main/resources/templates/release-notification.txt, submission/notifications/src/main/resources/templates/successful-submission.txt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt, submission/persistence-sql/src/main/kotlin/ac/uk/ebi/biostd/persistence/repositories/data/SubmissionRepository.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionResource.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/ext/ExtendedPageMapper.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionServiceTest.kt
https://www.pivotaltracker.com/story/show/172671360
- Log error instead of failing when getting extended submissions
- Fix notification messages
=> Pivotal ID # 172671360: Warn users about upcoming public release

submission/persistence-common/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/filesystem/FileSystemService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/ExternalConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequest.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceServiceTest.kt
https://www.pivotaltracker.com/story/show/177040448
=> Pivotal ID # 177040448: Store request as plain json

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt
https://www.pivotaltracker.com/story/show/177647985
Switch from full read file for MD5 calculation to a buffered reader approach
=> Pivotal # 177647985: MD5 Calculation For Big Files

infrastructure/build.gradle.kts, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/web/resources/UserFilesResource.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/files/web/UserFilesResourceTest.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/resolvers/TestUserPathResolver.kt
Additionally:
- Fixes `setUpDatabase` task
- Adds `setUpMongoDatabase` task
=> Send Content-Disposition and Content-Length headers while downloading files

infrastructure/src/main/resources/setup/rabbitmq/SetUpRabbitMQ.cmd, infrastructure/src/main/resources/setup/rabbitmq/SetUpRabbitMQ.sh
https://www.pivotaltracker.com/story/show/179024679
* Pin RabbitMQ container to 3.8-management (already used)
=> Pivotal ID # 179024679: Fix RabbitMQ version to 3.8

buildSrc/src/main/kotlin/Dependencies.kt, client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireAuthRequestInitializer.kt, client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireWebClient.kt, submission/submission-webapp/build.gradle.kts, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/WebConfig.kt
https://www.pivotaltracker.com/story/show/179609612
Configure the FIRE web client to handle the submission of large files:
- Set the maximum request size in the Rest Template to 20 GB
- Create a custom multipart resolver that is able to handle files of this size
- Add custom request initializer instead the interceptor in order to avoid replacing the request factory
=> Pivotal ID # 179609612: Submit Large Files To Fire

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/DeleteCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Parameters.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/SubmissionRequest.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommandTest.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommandTest.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartAsyncSubmissionClient.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmissionClient.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmissionClient.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/WebConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/converters/ExtAttributeDetailConverter.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/MultipartSubmitResource.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/submit/async/MultipartAsyncSubmitResource.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/converters/ExtAttributeDetailConverterTest.kt
https://www.pivotaltracker.com/story/show/179922324
-  Add an option to move files instead of copying in the CLI submit operations
- Adjust the involved endpoints and web client's methods
- Add a converter for the "attributes" parameter
=> Pivotal ID # 179922324: File Mode CLI Option

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt
https://www.pivotaltracker.com/story/show/181381956
If any active re-submission request exists, the currently processed submission shouldn't be displayed in the submission list
=> Pivotal ID # 181381956: Filter Active Requests For Existing Submissions

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommand.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommandTest.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommandTest.kt
https://www.pivotaltracker.com/story/show/181330026
- Fix failure when attached files option is not provided
- Normalise the code for the submit and submit async operations
=> Pivotal ID # 181330026: Attached Directory Should Not Be Required

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/api/FireClient.kt, client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/integration/web/FireOperations.kt, client/fire-webclient/src/test/kotlin/uk/ac/ebi/fire/client/api/FireClientTest.kt, commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensions.kt, commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtSubmissionExtensionsTest.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFtpService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFtpService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/pagetab/FirePageTabService.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/fire/FireFilesServiceTest.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/fire/FireFtpServiceTest.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/nfs/NfsFtpServiceTest.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/pagetab/FirePageTabServiceTest.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/common/TestWireMockTransformer.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FileSystemConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/FireResource.kt
https://www.pivotaltracker.com/story/show/181416527
- Set the path to the files of every submission even if these are private
- Clean submission folder before files processing
- Remove unnecessary parameter in the FIRE save operation
- Include referenced files in the releasing process
=> Pivotal ID # 181416527: Fixes for FIRE

client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionClient.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToFile.kt, commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/extended/mapping/to/ToFileTest.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/json/serialization/FileJsonSerializerTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/AllInOneSubmissionTsv.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/FireMockDatabase.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/handlers/QueryHandlers.kt
https://www.pivotaltracker.com/story/show/181807913
Add calculated MD5 to pagetab files
=> Pivotal ID # 181807913: Add MD5 To Pagetab

commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/stream/FileListTsvStreamDeserializer.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/tsv/FileListTsvStreamDeserializerTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/assertions/AllInOneSubmissionHelper.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/JsonSubmissionFactory.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/TsvSubmissionFactory.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/factory/XmlSubmissionFactory.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/AllInOneSubmissionTest.kt
- Include first list in the TSV file list serialization
- Add file list assertions to the itests
=> Pivotal # 182332696: TSV File List Serialization

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/api/FireWebClient.kt, client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/FireApiFile.kt, commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtendedModel.kt, commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt, commons/commons-util/src/main/kotlin/ebi/ac/uk/io/ext/FileExtensions.kt, commons/commons-util/src/test/kotlin/ebi/ac/uk/io/FileUtilsTest.kt, submission/persistence-filesystem/build.gradle.kts, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/ZipUtil.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
https://www.pivotaltracker.com/story/show/182800115
- handled 404 when not files found by md5.
- added zip file handling logic.
=> Pivotal ID # 182800115: Folder Submissions handling

submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/submit/async/MultipartAsyncSubmitResource.kt
https://www.pivotaltracker.com/story/show/182963527
Set the required flag to false in order to keep consistency with the rest of the endpoints
=> Pivotal ID # 182963527: Files Not Required For Submission Endpoints

client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/SubmissionRequest.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionService.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitAsyncCommandTest.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmitCommandTest.kt, client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/MultiPartSubmitClient.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/common/BioWebClientRequestBuilder.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmitClient.kt, scheduler/tasks/pmc-processor-task/src/main/kotlin/ac/uk/ebi/pmc/submit/PmcSubmitter.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeletePermissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionListApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListSubmissionTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/FileListValidationTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/MultipartFileSubmissionApiTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionToCollectionsTest.kt
https://www.pivotaltracker.com/story/show/183440873
- Include the storage mode in the files configuration
- Add the parameter to the submission request
- Update the tests
=> Pivotal ID # 183440873: Storage Mode Option Ignored By CLI

ci/update.sh, deploy.gradle
https://www.pivotaltracker.com/story/show/183817421
- Specify terminal stdout and stderr output streams to avoid the terminal being clogged
- Remove the "sh" command from the command execution since it's not required in standard linux shell
=> Pivotal ID # 183817421: Migrate DEV To HL

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/retry/RetryTemplateExtensions.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionDraftResource.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftServiceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionProcessor.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/SubmissionSubmitter.kt
https://www.pivotaltracker.com/story/show/183126684
- Include draft related information in the logs
- Change the logging level for the retry web template from error to warning
=> Pivotal ID # 183126684: Log Submission Draft ID

commons/commons-model-extended/src/main/kotlin/ebi/ac/uk/extended/model/ExtFileExtensions.kt, commons/commons-model-extended/src/test/kotlin/ebi/ac/uk/extended/model/ExtFileExtensionsTest.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/SubmissionFilesSource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestSaver.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestSaverTest.kt
https://www.pivotaltracker.com/story/show/184014407
- Set the proper attributes to a file that's referenced multiple times
- Change the referenced files method in order to support multiple file references
=> Pivotal ID # 184014407: Multiple Reference Files In Resubmission

submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/SubmitPermissionTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/AccNoService.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/service/AccNoServiceTest.kt
https://www.pivotaltracker.com/story/show/184014414
Give priority to owner's resubmission
=> Pivotal ID # 184014414: Permissions For Resubmission To Collection

submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesServiceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleaner.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleanerTest.kt
https://www.pivotaltracker.com/story/show/184772659
=> Pivotal ID # 184772659: Delete only common files when required on re submission

commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/to/ToFileListMapper.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/Repositories.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionQueryService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionQueryService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionQueryResource.kt
https://www.pivotaltracker.com/story/show/184812856
- added file list pagetab generation endpoints
=> Pivotal ID # 184812856: Regenerate pagetab operation 

commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/FileSourcesList.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/io/sources/FilesSource.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/BioFile.kt, commons/commons-bio/src/main/kotlin/ebi/ac/uk/model/constants/Fields.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/extended/mapping/from/ToExtFile.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/io/sources/FilesListSource.kt, commons/commons-model-extended-mapping/src/main/kotlin/ebi/ac/uk/io/sources/PathSource.kt, commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/io/sources/FileSourcesListTest.kt, commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/io/sources/FilesListSourceTest.kt, commons/commons-model-extended-mapping/src/test/kotlin/ebi/ac/uk/io/sources/PathSourceTest.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/json/deserialization/FileJsonDeserializer.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/service/PageTabFileReader.kt, commons/commons-serialization/src/main/kotlin/ac/uk/ebi/biostd/tsv/deserialization/model/TsvChunk.kt, commons/commons-serialization/src/test/kotlin/ac/uk/ebi/biostd/service/PageTabFileReaderTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionDraftService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/DbFilesSource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/FireFilesSource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/SubmissionFilesSource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/model/GroupSource.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/service/FileSourcesService.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/validator/filelist/FileListValidator.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactoryTest.kt
https://www.pivotaltracker.com/story/show/184779579
- added file type to serialization
=> Pivotal ID # 184779579: Match generated zip with user folders Collapse

submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FileStorageService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/api/FilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesService.kt, submission/persistence-filesystem/src/main/kotlin/ac/uk/ebi/biostd/persistence/filesystem/service/StorageService.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/fire/FireFilesServiceTest.kt, submission/persistence-filesystem/src/test/kotlin/ac/uk/ebi/biostd/persistence/filesystem/nfs/NfsFilesServiceTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/FilePersistenceConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionService.kt, submission/submission-webapp/src/main/resources/application.yml, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleaner.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestFinalizer.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestCleanerTest.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/submitter/request/SubmissionRequestFinalizerTest.kt
https://www.pivotaltracker.com/story/show/184822139
- simplified code to have a single delete files operation.
=> Pivotal ID # 184822139: Delete Submission Folder After Resubmission

client/fire-webclient/src/main/kotlin/uk/ac/ebi/fire/client/model/FireApiFile.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/FireMockDatabase.kt
- Remove the initial slash from FIRE responses
- Normalize FIRE mock output to mimic the original service response
=> Pivotal ID # 185273996: Fire s3 path should be relative

.gitlab-ci.yml, submission/file-sources/src/main/kotlin/uk/ac/ebi/io/sources/SubmissionFilesSource.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/ToExtSubmissionConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoFilesPersistenceService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoPersistenceQueryService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoFilesPersistenceServiceTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoQueryServiceTest.kt, submission/submission-security/src/test/kotlin/ebi/ac/uk/security/util/SecurityUtilTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionFileSourceTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/GeneralConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/ExtSubmissionQueryService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionQueryService.kt, submission/submission-webapp/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/service/ext/ExtSubmissionPersistenceQueryServiceTest.kt, submission/submitter/src/main/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactory.kt, submission/submitter/src/test/kotlin/ac/uk/ebi/biostd/submission/helpers/FilesSourceFactoryTest.kt
https://www.pivotaltracker.com/story/show/183230982
PR # 2/4
- Refactor out the methods related to the referenced files in the persistence layer in order to isolate this logic from the whole submission
- Fix a couple of "TooManyFunctions" warning
- Fix typos
- Change gitlab build from concurrent to sequential
=> Pivotal ID # 183230982: Avoid Special Characters In File Paths

submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/common/Constants.kt, submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/ApplicationConfig.kt, submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SecurityNotificationListener.kt, submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt, submission/submission-handlers/src/main/resources/application.yml, submission/submission-handlers/src/test/kotlin/ac/uk/ebi/biostd/handlers/listeners/SecurityNotificationListenerTest.kt
https://www.pivotaltracker.com/story/show/185460059
- Catch errors on security notifications
- Use spring logs rolling back policy in order to compress the old log files
=> Pivotal ID # 185460059: Retry E-Mails Only Once

.gitlab-ci.yml, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/itest/ITestListener.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionPerformanceTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/wiremock/TestWireMockTransformer.kt
https://www.pivotaltracker.com/story/show/185786866
=> Pivotal ID # 185786866: Simple automated performance test

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/FileListDocFileDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDraftDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/ToExtSubmissionConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileListMapper.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/CollectionMongoDataService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/StatsMongoDataService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionMongoFilesPersistenceService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestFilesMongoPersistenceService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionDocDataRepositoryTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepositoryTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/repositories/FileListDocFileRepositoryTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/mapping/to/ToExtFileListMapperTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionRefreshApiTest.kt
=> Pivotal ID # 185788503: Reactive Mongo

.gitlab-ci.yml, commons/commons-bio/src/main/kotlin/ebi/ac/uk/errors/InvalidPathException.kt, commons/commons-bio/src/test/kotlin/ebi/ac/uk/io/sources/FileSourcesListTest.kt, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/submit/SubmissionApiTest.kt
https://www.pivotaltracker.com/story/show/185649200
- Include the file list help url in the error message for invalid paths
- Include the task to auto deploy the stats reporter task which was forgotten in a previous PR
=> Pivotal ID # 185649200: Cater For Paths Ending With Backslash

commons/commons-util/src/main/kotlin/ebi/ac/uk/io/FileUtils.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/utils/MultipartFileUtils.kt
https://www.pivotaltracker.com/story/show/186496317
- Improve method signature
- Close InputStream after using it
=> Pivotal ID # 186496317: Too Many Open Files

client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/ClusterClient.kt, client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/LocalClusterClient.kt, client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/RemoteClusterClient.kt, client/ftp-webclient/src/main/kotlin/ebi/ac/uk/ftp/SimpleFtpClient.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/files/service/ftp/FtpFileService.kt
https://www.pivotaltracker.com/story/show/186637755
- re use same connection
=> Pivotal ID # 186637755: Re use same FTP connection for multiple file uploads

submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtSubmissionSubmitter.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtendedSubmissionSubmitter.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/LocalExtSubmissionSubmitter.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/RemoteExtSubmissionSubmitter.kt, submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/extended/LocalExtSubmissionSubmitterTest.kt, submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/submitter/ExtendedSubmissionSubmitterTest.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/common/config/SubmissionWebConfig.kt
https://www.pivotaltracker.com/story/show/186657295
- Handle re-triggering for submissions executed remotely
=> Pivotal ID # 186657295: Retrigger Submission Task

client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/ClusterClient.kt, client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/LocalClusterClient.kt, client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/RemoteClusterClient.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/cluster/web/ClusterOperationsResource.kt
https://www.pivotaltracker.com/story/show/186609885
- added logs api
=> Pivotal ID # 186609885: Access cluster logs admin API

submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/HandlersApplication.kt, submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/config/ApplicationConfig.kt, submission/submission-handlers/src/main/kotlin/ac/uk/ebi/biostd/handlers/listeners/SubmissionNotificationsListener.kt
https://www.pivotaltracker.com/story/show/187104619
- Fix buffer size for the handler web client
- Improve error logging for failed notifications
=> Pivotal # 187104619: Submission Notification Listener WebClient Buffer Size

buildSrc/src/main/kotlin/Dependencies.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/lock/DistributedLockExecutor.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceServiceTest.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestCleaner.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoader.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestProcessor.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestReleaser.kt, submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestLoaderTest.kt, submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestProcessorTest.kt, submission/submission-core/src/test/kotlin/ac/uk/ebi/biostd/submission/domain/request/SubmissionRequestReleaserTest.kt
https://www.pivotaltracker.com/story/show/187456681
- unified update request operation
- increased lock duration
=> Pivotal ID # 187456681: Submission request file status

.gitlab-ci.yml, build.gradle.kts, buildSrc/src/main/kotlin/Plugins.kt, ci/bio-commandline.yml, ci/exporter.yml, ci/pmc-processor.yml, ci/scheduler.yml, ci/stats-reporter.yml, ci/submission-handlers.yml, ci/submission-migrator.yml, ci/submission-releaser.yml, ci/submission-task.yml, ci/submitter.yml, deploy.gradle, infrastructure/build.gradle.kts
https://www.pivotaltracker.com/story/show/187611460
Generate the corresponding artifact during the deployment stage execution
=> Pivotal ID # 187611460: Fix Artifacts Deployment

client/bio-commandline/src/test/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionServiceTest.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionRequestClient.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/integration/web/SubmitClient.kt, commons/commons-test/src/main/kotlin/ebi/ac/uk/db/DatabaseConstants.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/service/SubmissionOperations.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/converters/shared/ConverterCommonsFields.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestFilesDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbReposConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/integration/MongoDbServicesConfig.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/model/SubmissionRequestModel.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestFilesMongoPersistenceService.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceService.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepositoryTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestFilesMongoPersistenceServiceTest.kt, submission/persistence-mongo/src/test/kotlin/ac/uk/ebi/biostd/persistence/doc/service/SubmissionRequestMongoPersistenceServiceTest.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/extended/ExtSubmissionService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/domain/service/SubmissionRequestService.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/submission/web/resources/SubmissionRequestResource.kt
https://www.pivotaltracker.com/story/show/188131969
- added archieve rest operation
=> Pivotal ID # 188131969: Archieve submission request

client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/api/LsfClusterClient.kt, client/cluster-client/src/main/kotlin/uk/ac/ebi/biostd/client/cluster/model/Cluster.kt, scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/ExporterProperties.kt, scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterProperties.kt, scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/StatsReporterProperties.kt, scheduler/common/task-properties/src/main/kotlin/ac/uk/ebi/scheduler/properties/SubmissionReleaserProperties.kt, scheduler/common/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/ExporterPropertiesTest.kt, scheduler/common/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/PmcImporterPropertiesTest.kt, scheduler/common/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/StatsReporterPropertiesTest.kt, scheduler/common/task-properties/src/test/kotlin/ac/uk/ebi/scheduler/properties/SubmissionReleaserPropertiesTest.kt, scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/config/SchedulerConfig.kt, scheduler/scheduler/src/main/kotlin/uk/ac/ebi/scheduler/common/properties/AppProperties.kt, scheduler/scheduler/src/main/resources/application.yml, scheduler/scheduler/src/test/kotlin/uk/ac/ebi/scheduler/pmc/exporter/domain/ExporterTriggerTest.kt, scheduler/scheduler/src/test/kotlin/uk/ac/ebi/scheduler/releaser/domain/SubmissionReleaserTriggerTest.kt, scheduler/scheduler/src/test/kotlin/uk/ac/ebi/scheduler/stats/domain/StatsReporterTriggerTest.kt, submission/submission-config/build.gradle.kts, submission/submission-config/src/main/kotlin/ac/uk/ebi/biostd/common/properties/ClusterProperties.kt, submission/submission-core/src/main/kotlin/ac/uk/ebi/biostd/submission/config/GeneralConfig.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/cluster/web/ClusterExecutor.kt, submission/submission-webapp/src/main/kotlin/ac/uk/ebi/biostd/cluster/web/ClusterOperationsResource.kt
https://www.pivotaltracker.com/story/show/188114384
- Create common Cluster config class
- Add option to execute scheduler jobs in SLURM
=> Pivotal ID # 188114384: Scheduler SLURM Migration

client/bio-commandline/README.md, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/BioStudiesCommandLine.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/commands/SubmissionRequestStatusCommand.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/common/Parameters.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/dto/SubmissionStatusRequest.kt, client/bio-commandline/src/main/kotlin/uk/ac/ebi/biostd/client/cli/services/SubmissionRequestService.kt, client/bio-webclient/src/main/kotlin/ac/uk/ebi/biostd/client/api/SubmissionRequestClient.kt, submission/persistence-common-api/src/main/kotlin/ac/uk/ebi/biostd/persistence/common/exception/SubmissionRequestNotFoundException.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/data/SubmissionRequestDocDataRepository.kt, submission/persistence-mongo/src/main/kotlin/ac/uk/ebi/biostd/persistence/doc/db/reactive/repositories/Repositories.kt, submission/submission-webapp/src/itest/itestsInventory.md, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/submission/query/SubmissionRequestApiTest.kt
https://www.pivotaltracker.com/story/show/188035630
- Create command to get a request status
- Fix operation method in the web client
- Handle scenario for request not found
=> Pivotal ID # 188035630: Request Status CLI Operation

submission/submission-security/src/main/kotlin/ebi/ac/uk/security/service/UserPrivilegesService.kt, submission/submission-webapp/src/itest/itestsInventory.md, submission/submission-webapp/src/itest/kotlin/ac/uk/ebi/biostd/itest/test/security/DeleteFilesPermissionTest.kt
https://www.pivotaltracker.com/story/show/188837317
- Update logic to allow admin users to delete files on public submissions
- Update iTests to use regular user web client
=> Pivotal ID # 188837317: Allow Files Deletion For Collection ADMIN
